package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.AccExtract;
import com.joyveb.cashmanage.entity.AccExtractExample;
import com.joyveb.cashmanage.entity.AccExtractKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AccExtractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @SelectProvider(type=AccExtractSqlProvider.class, method="countByExample")
    int countByExample(AccExtractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @DeleteProvider(type=AccExtractSqlProvider.class, method="deleteByExample")
    int deleteByExample(AccExtractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @Delete({
        "delete from t_acc_extract",
        "where USERNAME = #{username,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(AccExtractKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @Insert({
        "insert into t_acc_extract (USERNAME, MONEY, ",
        "ALIPAYNUM, STATUS)",
        "values (#{username,jdbcType=VARCHAR}, #{money,jdbcType=DECIMAL}, ",
        "#{alipaynum,jdbcType=VARCHAR}, #{status,jdbcType=CHAR})"
    })
    int insert(AccExtract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @InsertProvider(type=AccExtractSqlProvider.class, method="insertSelective")
    int insertSelective(AccExtract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @SelectProvider(type=AccExtractSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="USERNAME", property="username", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="MONEY", property="money", jdbcType= JdbcType.DECIMAL),
        @Result(column="ALIPAYNUM", property="alipaynum", jdbcType= JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType= JdbcType.CHAR)
    })
    List<AccExtract> selectByExample(AccExtractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @Select({
        "select",
        "USERNAME, MONEY, ALIPAYNUM, STATUS",
        "from t_acc_extract",
        "where USERNAME = #{username,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="USERNAME", property="username", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="MONEY", property="money", jdbcType= JdbcType.DECIMAL),
        @Result(column="ALIPAYNUM", property="alipaynum", jdbcType= JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType= JdbcType.CHAR)
    })
    AccExtract selectByPrimaryKey(AccExtractKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @UpdateProvider(type=AccExtractSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AccExtract record, @Param("example") AccExtractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @UpdateProvider(type=AccExtractSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AccExtract record, @Param("example") AccExtractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @UpdateProvider(type=AccExtractSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AccExtract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_extract
     *
     * @mbggenerated Thu Aug 17 21:15:13 CST 2017
     */
    @Update({
        "update t_acc_extract",
        "set MONEY = #{money,jdbcType=DECIMAL},",
          "ALIPAYNUM = #{alipaynum,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=CHAR}",
        "where USERNAME = #{username,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AccExtract record);
}