package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.AccNeightCheck;
import com.joyveb.cashmanage.entity.AccNeightCheckExample;
import com.joyveb.cashmanage.entity.AccNeightCheckKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AccNeightCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @SelectProvider(type=AccNeightCheckSqlProvider.class, method="countByExample")
    int countByExample(AccNeightCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @DeleteProvider(type=AccNeightCheckSqlProvider.class, method="deleteByExample")
    int deleteByExample(AccNeightCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @Delete({
        "delete from t_acc_neight_check",
        "where DATE = #{date,jdbcType=VARCHAR}",
          "and USERNAME = #{username,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(AccNeightCheckKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @Insert({
        "insert into t_acc_neight_check (DATE, USERNAME, ",
        "MONEY)",
        "values (#{date,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{money,jdbcType=DECIMAL})"
    })
    int insert(AccNeightCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @InsertProvider(type=AccNeightCheckSqlProvider.class, method="insertSelective")
    int insertSelective(AccNeightCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @SelectProvider(type=AccNeightCheckSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="DATE", property="date", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="USERNAME", property="username", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="MONEY", property="money", jdbcType= JdbcType.DECIMAL)
    })
    List<AccNeightCheck> selectByExample(AccNeightCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @Select({
        "select",
        "DATE, USERNAME, MONEY",
        "from t_acc_neight_check",
        "where DATE = #{date,jdbcType=VARCHAR}",
          "and USERNAME = #{username,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="DATE", property="date", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="USERNAME", property="username", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="MONEY", property="money", jdbcType= JdbcType.DECIMAL)
    })
    AccNeightCheck selectByPrimaryKey(AccNeightCheckKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @UpdateProvider(type=AccNeightCheckSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AccNeightCheck record, @Param("example") AccNeightCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @UpdateProvider(type=AccNeightCheckSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AccNeightCheck record, @Param("example") AccNeightCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @UpdateProvider(type=AccNeightCheckSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AccNeightCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_neight_check
     *
     * @mbggenerated Fri Aug 18 11:16:51 CST 2017
     */
    @Update({
        "update t_acc_neight_check",
        "set MONEY = #{money,jdbcType=DECIMAL}",
        "where DATE = #{date,jdbcType=VARCHAR}",
          "and USERNAME = #{username,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AccNeightCheck record);
}