package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.AccWhitelistParent;
import com.joyveb.cashmanage.entity.AccWhitelistParentExample;
import com.joyveb.cashmanage.entity.AccWhitelistParentExample.Criteria;
import com.joyveb.cashmanage.entity.AccWhitelistParentExample.Criterion;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class AccWhitelistParentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    public String countByExample(AccWhitelistParentExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("t_acc_whitelist_parent");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    public String deleteByExample(AccWhitelistParentExample example) {
        BEGIN();
        DELETE_FROM("t_acc_whitelist_parent");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    public String insertSelective(AccWhitelistParent record) {
        BEGIN();
        INSERT_INTO("t_acc_whitelist_parent");
        
        if (record.getUsername() != null) {
            VALUES("USERNAME", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getFullname() != null) {
            VALUES("FULLNAME", "#{fullname,jdbcType=VARCHAR}");
        }
        
        if (record.getIdcard() != null) {
            VALUES("IDCARD", "#{idcard,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            VALUES("MOBILE", "#{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            VALUES("ADDRESS", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("STATUS", "#{status,jdbcType=CHAR}");
        }
        
        if (record.getCommission() != null) {
            VALUES("COMMISSION", "#{commission,jdbcType=VARCHAR}");
        }
        
        if (record.getAlipaynum() != null) {
            VALUES("ALIPAYNUM", "#{alipaynum,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            VALUES("COMMENT", "#{comment,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            VALUES("CREATETIME", "#{createtime,jdbcType=BIGINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    public String selectByExample(AccWhitelistParentExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("USERNAME");
        } else {
            SELECT("USERNAME");
        }
        SELECT("FULLNAME");
        SELECT("IDCARD");
        SELECT("MOBILE");
        SELECT("ADDRESS");
        SELECT("STATUS");
        SELECT("COMMISSION");
        SELECT("ALIPAYNUM");
        SELECT("COMMENT");
        SELECT("CREATETIME");
        FROM("t_acc_whitelist_parent");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AccWhitelistParent record = (AccWhitelistParent) parameter.get("record");
        AccWhitelistParentExample example = (AccWhitelistParentExample) parameter.get("example");
        
        BEGIN();
        UPDATE("t_acc_whitelist_parent");
        
        if (record!=null && record.getUsername() != null) {
            SET("USERNAME = #{record.username,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getFullname() != null) {
            SET("FULLNAME = #{record.fullname,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getIdcard() != null) {
            SET("IDCARD = #{record.idcard,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getMobile() != null) {
            SET("MOBILE = #{record.mobile,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getAddress() != null) {
            SET("ADDRESS = #{record.address,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getStatus() != null) {
            SET("STATUS = #{record.status,jdbcType=CHAR}");
        }
        
        if (record!=null && record.getCommission() != null) {
            SET("COMMISSION = #{record.commission,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getAlipaynum() != null) {
            SET("ALIPAYNUM = #{record.alipaynum,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getComment() != null) {
            SET("COMMENT = #{record.comment,jdbcType=VARCHAR}");
        }
        
        if (record!=null && record.getCreatetime() != null) {
            SET("CREATETIME = #{record.createtime,jdbcType=BIGINT}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("t_acc_whitelist_parent");
        
        SET("USERNAME = #{record.username,jdbcType=VARCHAR}");
        SET("FULLNAME = #{record.fullname,jdbcType=VARCHAR}");
        SET("IDCARD = #{record.idcard,jdbcType=VARCHAR}");
        SET("MOBILE = #{record.mobile,jdbcType=VARCHAR}");
        SET("ADDRESS = #{record.address,jdbcType=VARCHAR}");
        SET("STATUS = #{record.status,jdbcType=CHAR}");
        SET("COMMISSION = #{record.commission,jdbcType=VARCHAR}");
        SET("ALIPAYNUM = #{record.alipaynum,jdbcType=VARCHAR}");
        SET("COMMENT = #{record.comment,jdbcType=VARCHAR}");
        SET("CREATETIME = #{record.createtime,jdbcType=BIGINT}");
        
        AccWhitelistParentExample example = (AccWhitelistParentExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    public String updateByPrimaryKeySelective(AccWhitelistParent record) {
        BEGIN();
        UPDATE("t_acc_whitelist_parent");
        
        if (record.getFullname() != null) {
            SET("FULLNAME = #{fullname,jdbcType=VARCHAR}");
        }
        
        if (record.getIdcard() != null) {
            SET("IDCARD = #{idcard,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            SET("MOBILE = #{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            SET("ADDRESS = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{status,jdbcType=CHAR}");
        }
        
        if (record.getCommission() != null) {
            SET("COMMISSION = #{commission,jdbcType=VARCHAR}");
        }
        
        if (record.getAlipaynum() != null) {
            SET("ALIPAYNUM = #{alipaynum,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            SET("COMMENT = #{comment,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            SET("CREATETIME = #{createtime,jdbcType=BIGINT}");
        }
        
        WHERE("USERNAME = #{username,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist_parent
     *
     * @mbggenerated Thu Aug 17 20:06:15 CST 2017
     */
    protected void applyWhere(AccWhitelistParentExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}