package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.DbProperties;
import com.joyveb.cashmanage.entity.DbPropertiesExample;
import com.joyveb.cashmanage.entity.DbPropertiesKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DbPropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @SelectProvider(type=DbPropertiesSqlProvider.class, method="countByExample")
    int countByExample(DbPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @DeleteProvider(type=DbPropertiesSqlProvider.class, method="deleteByExample")
    int deleteByExample(DbPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @Delete({
        "delete from t_manage_dbproperties",
        "where THEKEY = #{thekey,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(DbPropertiesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @Insert({
        "insert into t_manage_dbproperties (THEKEY, VALUE, ",
        "DES)",
        "values (#{thekey,jdbcType=VARCHAR}, #{value,jdbcType=VARCHAR}, ",
        "#{des,jdbcType=VARCHAR})"
    })
    int insert(DbProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @InsertProvider(type=DbPropertiesSqlProvider.class, method="insertSelective")
    int insertSelective(DbProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @SelectProvider(type=DbPropertiesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="THEKEY", property="thekey", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="VALUE", property="value", jdbcType=JdbcType.VARCHAR),
        @Result(column="DES", property="des", jdbcType=JdbcType.VARCHAR)
    })
    List<DbProperties> selectByExample(DbPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @Select({
        "select",
        "THEKEY, VALUE, DES",
        "from t_manage_dbproperties",
        "where THEKEY = #{thekey,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="THEKEY", property="thekey", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="VALUE", property="value", jdbcType=JdbcType.VARCHAR),
        @Result(column="DES", property="des", jdbcType=JdbcType.VARCHAR)
    })
    DbProperties selectByPrimaryKey(DbPropertiesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @UpdateProvider(type=DbPropertiesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DbProperties record, @Param("example") DbPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @UpdateProvider(type=DbPropertiesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DbProperties record, @Param("example") DbPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @UpdateProvider(type=DbPropertiesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DbProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @Update({
        "update t_manage_dbproperties",
        "set VALUE = #{value,jdbcType=VARCHAR},",
          "DES = #{des,jdbcType=VARCHAR}",
        "where THEKEY = #{thekey,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(DbProperties record);
}