package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.GameOut;
import com.joyveb.cashmanage.entity.GameOutExample;
import com.joyveb.cashmanage.entity.GameOutKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GameOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @SelectProvider(type=GameOutSqlProvider.class, method="countByExample")
    int countByExample(GameOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @DeleteProvider(type=GameOutSqlProvider.class, method="deleteByExample")
    int deleteByExample(GameOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @Delete({
        "delete from t_game_out",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(GameOutKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @Insert({
        "insert into t_game_out (UUID, GAMECODE, ",
        "PRODUCTBATCH, BOOKNUM, ",
        "OUTTIME, OUTPERSON, ",
        "ORDERID)",
        "values (#{uuid,jdbcType=VARCHAR}, #{gamecode,jdbcType=VARCHAR}, ",
        "#{productbatch,jdbcType=VARCHAR}, #{booknum,jdbcType=VARCHAR}, ",
        "#{outtime,jdbcType=BIGINT}, #{outperson,jdbcType=VARCHAR}, ",
        "#{orderid,jdbcType=VARCHAR})"
    })
    int insert(GameOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @InsertProvider(type=GameOutSqlProvider.class, method="insertSelective")
    int insertSelective(GameOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @SelectProvider(type=GameOutSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTBATCH", property="productbatch", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOKNUM", property="booknum", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUTTIME", property="outtime", jdbcType=JdbcType.BIGINT),
        @Result(column="OUTPERSON", property="outperson", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERID", property="orderid", jdbcType=JdbcType.VARCHAR)
    })
    List<GameOut> selectByExample(GameOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @Select({
        "select",
        "UUID, GAMECODE, PRODUCTBATCH, BOOKNUM, OUTTIME, OUTPERSON, ORDERID",
        "from t_game_out",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTBATCH", property="productbatch", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOKNUM", property="booknum", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUTTIME", property="outtime", jdbcType=JdbcType.BIGINT),
        @Result(column="OUTPERSON", property="outperson", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERID", property="orderid", jdbcType=JdbcType.VARCHAR)
    })
    GameOut selectByPrimaryKey(GameOutKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @UpdateProvider(type=GameOutSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GameOut record, @Param("example") GameOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @UpdateProvider(type=GameOutSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GameOut record, @Param("example") GameOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @UpdateProvider(type=GameOutSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GameOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @Update({
        "update t_game_out",
        "set GAMECODE = #{gamecode,jdbcType=VARCHAR},",
          "PRODUCTBATCH = #{productbatch,jdbcType=VARCHAR},",
          "BOOKNUM = #{booknum,jdbcType=VARCHAR},",
          "OUTTIME = #{outtime,jdbcType=BIGINT},",
          "OUTPERSON = #{outperson,jdbcType=VARCHAR},",
          "ORDERID = #{orderid,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GameOut record);
}