package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.GameInfo;
import com.joyveb.cashmanage.entity.GameInfoExample;
import com.joyveb.cashmanage.entity.GameInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GameInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @SelectProvider(type=GameInfoSqlProvider.class, method="countByExample")
    int countByExample(GameInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @DeleteProvider(type=GameInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(GameInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @Delete({
        "delete from t_game_info",
        "where GAMECODE = #{gamecode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(GameInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @Insert({
        "insert into t_game_info (GAMECODE, GAMENAME, ",
        "PREVIEWPATH, DETAILEDPATH, ",
        "FACEVALUE, GAMETYPE, ",
        "GAMEPRICE)",
        "values (#{gamecode,jdbcType=VARCHAR}, #{gamename,jdbcType=VARCHAR}, ",
        "#{previewpath,jdbcType=VARCHAR}, #{detailedpath,jdbcType=VARCHAR}, ",
        "#{facevalue,jdbcType=INTEGER}, #{gametype,jdbcType=VARCHAR}, ",
        "#{gameprice,jdbcType=INTEGER})"
    })
    int insert(GameInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @InsertProvider(type=GameInfoSqlProvider.class, method="insertSelective")
    int insertSelective(GameInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @SelectProvider(type=GameInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GAMENAME", property="gamename", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREVIEWPATH", property="previewpath", jdbcType=JdbcType.VARCHAR),
        @Result(column="DETAILEDPATH", property="detailedpath", jdbcType=JdbcType.VARCHAR),
        @Result(column="FACEVALUE", property="facevalue", jdbcType=JdbcType.INTEGER),
        @Result(column="GAMETYPE", property="gametype", jdbcType=JdbcType.VARCHAR),
        @Result(column="GAMEPRICE", property="gameprice", jdbcType=JdbcType.INTEGER)
    })
    List<GameInfo> selectByExample(GameInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @Select({
        "select",
        "GAMECODE, GAMENAME, PREVIEWPATH, DETAILEDPATH, FACEVALUE, GAMETYPE, GAMEPRICE",
        "from t_game_info",
        "where GAMECODE = #{gamecode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GAMENAME", property="gamename", jdbcType=JdbcType.VARCHAR),
        @Result(column="PREVIEWPATH", property="previewpath", jdbcType=JdbcType.VARCHAR),
        @Result(column="DETAILEDPATH", property="detailedpath", jdbcType=JdbcType.VARCHAR),
        @Result(column="FACEVALUE", property="facevalue", jdbcType=JdbcType.INTEGER),
        @Result(column="GAMETYPE", property="gametype", jdbcType=JdbcType.VARCHAR),
        @Result(column="GAMEPRICE", property="gameprice", jdbcType=JdbcType.INTEGER)
    })
    GameInfo selectByPrimaryKey(GameInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @UpdateProvider(type=GameInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GameInfo record, @Param("example") GameInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @UpdateProvider(type=GameInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GameInfo record, @Param("example") GameInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @UpdateProvider(type=GameInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GameInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    @Update({
        "update t_game_info",
        "set GAMENAME = #{gamename,jdbcType=VARCHAR},",
          "PREVIEWPATH = #{previewpath,jdbcType=VARCHAR},",
          "DETAILEDPATH = #{detailedpath,jdbcType=VARCHAR},",
          "FACEVALUE = #{facevalue,jdbcType=INTEGER},",
          "GAMETYPE = #{gametype,jdbcType=VARCHAR},",
          "GAMEPRICE = #{gameprice,jdbcType=INTEGER}",
        "where GAMECODE = #{gamecode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GameInfo record);
}