package com.joyveb.cashmanage.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.joyveb.cashmanage.entity.GameInfo;
import com.joyveb.cashmanage.entity.GameInfoExample.Criteria;
import com.joyveb.cashmanage.entity.GameInfoExample.Criterion;
import com.joyveb.cashmanage.entity.GameInfoExample;
import java.util.List;
import java.util.Map;

public class GameInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    public String countByExample(GameInfoExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("t_game_info");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    public String deleteByExample(GameInfoExample example) {
        BEGIN();
        DELETE_FROM("t_game_info");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    public String insertSelective(GameInfo record) {
        BEGIN();
        INSERT_INTO("t_game_info");
        
        if (record.getGamecode() != null) {
            VALUES("GAMECODE", "#{gamecode,jdbcType=VARCHAR}");
        }
        
        if (record.getGamename() != null) {
            VALUES("GAMENAME", "#{gamename,jdbcType=VARCHAR}");
        }
        
        if (record.getPreviewpath() != null) {
            VALUES("PREVIEWPATH", "#{previewpath,jdbcType=VARCHAR}");
        }
        
        if (record.getDetailedpath() != null) {
            VALUES("DETAILEDPATH", "#{detailedpath,jdbcType=VARCHAR}");
        }
        
        if (record.getFacevalue() != null) {
            VALUES("FACEVALUE", "#{facevalue,jdbcType=INTEGER}");
        }
        
        if (record.getGametype() != null) {
            VALUES("GAMETYPE", "#{gametype,jdbcType=VARCHAR}");
        }
        
        if (record.getGameprice() != null) {
            VALUES("GAMEPRICE", "#{gameprice,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    public String selectByExample(GameInfoExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("GAMECODE");
        } else {
            SELECT("GAMECODE");
        }
        SELECT("GAMENAME");
        SELECT("PREVIEWPATH");
        SELECT("DETAILEDPATH");
        SELECT("FACEVALUE");
        SELECT("GAMETYPE");
        SELECT("GAMEPRICE");
        FROM("t_game_info");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        GameInfo record = (GameInfo) parameter.get("record");
        GameInfoExample example = (GameInfoExample) parameter.get("example");
        
        BEGIN();
        UPDATE("t_game_info");
        
        if (record.getGamecode() != null) {
            SET("GAMECODE = #{record.gamecode,jdbcType=VARCHAR}");
        }
        
        if (record.getGamename() != null) {
            SET("GAMENAME = #{record.gamename,jdbcType=VARCHAR}");
        }
        
        if (record.getPreviewpath() != null) {
            SET("PREVIEWPATH = #{record.previewpath,jdbcType=VARCHAR}");
        }
        
        if (record.getDetailedpath() != null) {
            SET("DETAILEDPATH = #{record.detailedpath,jdbcType=VARCHAR}");
        }
        
        if (record.getFacevalue() != null) {
            SET("FACEVALUE = #{record.facevalue,jdbcType=INTEGER}");
        }
        
        if (record.getGametype() != null) {
            SET("GAMETYPE = #{record.gametype,jdbcType=VARCHAR}");
        }
        
        if (record.getGameprice() != null) {
            SET("GAMEPRICE = #{record.gameprice,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("t_game_info");
        
        SET("GAMECODE = #{record.gamecode,jdbcType=VARCHAR}");
        SET("GAMENAME = #{record.gamename,jdbcType=VARCHAR}");
        SET("PREVIEWPATH = #{record.previewpath,jdbcType=VARCHAR}");
        SET("DETAILEDPATH = #{record.detailedpath,jdbcType=VARCHAR}");
        SET("FACEVALUE = #{record.facevalue,jdbcType=INTEGER}");
        SET("GAMETYPE = #{record.gametype,jdbcType=VARCHAR}");
        SET("GAMEPRICE = #{record.gameprice,jdbcType=INTEGER}");
        
        GameInfoExample example = (GameInfoExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    public String updateByPrimaryKeySelective(GameInfo record) {
        BEGIN();
        UPDATE("t_game_info");
        
        if (record.getGamename() != null) {
            SET("GAMENAME = #{gamename,jdbcType=VARCHAR}");
        }
        
        if (record.getPreviewpath() != null) {
            SET("PREVIEWPATH = #{previewpath,jdbcType=VARCHAR}");
        }
        
        if (record.getDetailedpath() != null) {
            SET("DETAILEDPATH = #{detailedpath,jdbcType=VARCHAR}");
        }
        
        if (record.getFacevalue() != null) {
            SET("FACEVALUE = #{facevalue,jdbcType=INTEGER}");
        }
        
        if (record.getGametype() != null) {
            SET("GAMETYPE = #{gametype,jdbcType=VARCHAR}");
        }
        
        if (record.getGameprice() != null) {
            SET("GAMEPRICE = #{gameprice,jdbcType=INTEGER}");
        }
        
        WHERE("GAMECODE = #{gamecode,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_info
     *
     * @mbggenerated Mon Oct 31 17:29:43 CST 2016
     */
    protected void applyWhere(GameInfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}