package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.GameInput;
import com.joyveb.cashmanage.entity.GameInputExample;
import com.joyveb.cashmanage.entity.GameInputKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GameInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @SelectProvider(type=GameInputSqlProvider.class, method="countByExample")
    int countByExample(GameInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @DeleteProvider(type=GameInputSqlProvider.class, method="deleteByExample")
    int deleteByExample(GameInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @Delete({
        "delete from t_game_input",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(GameInputKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @Insert({
        "insert into t_game_input (UUID, GAMECODE, ",
        "PRODUCTBATCH, BOOKNUM, ",
        "INPUTTIME, INPUTPERSON, ",
        "ISONSALE, ONSALETIME)",
        "values (#{uuid,jdbcType=VARCHAR}, #{gamecode,jdbcType=VARCHAR}, ",
        "#{productbatch,jdbcType=VARCHAR}, #{booknum,jdbcType=VARCHAR}, ",
        "#{inputtime,jdbcType=BIGINT}, #{inputperson,jdbcType=VARCHAR}, ",
        "#{isonsale,jdbcType=CHAR}, #{onsaletime,jdbcType=BIGINT})"
    })
    int insert(GameInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @InsertProvider(type=GameInputSqlProvider.class, method="insertSelective")
    int insertSelective(GameInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @SelectProvider(type=GameInputSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTBATCH", property="productbatch", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOKNUM", property="booknum", jdbcType=JdbcType.VARCHAR),
        @Result(column="INPUTTIME", property="inputtime", jdbcType=JdbcType.BIGINT),
        @Result(column="INPUTPERSON", property="inputperson", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISONSALE", property="isonsale", jdbcType=JdbcType.CHAR),
        @Result(column="ONSALETIME", property="onsaletime", jdbcType=JdbcType.BIGINT)
    })
    List<GameInput> selectByExample(GameInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @Select({
        "select",
        "UUID, GAMECODE, PRODUCTBATCH, BOOKNUM, INPUTTIME, INPUTPERSON, ISONSALE, ONSALETIME",
        "from t_game_input",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTBATCH", property="productbatch", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOKNUM", property="booknum", jdbcType=JdbcType.VARCHAR),
        @Result(column="INPUTTIME", property="inputtime", jdbcType=JdbcType.BIGINT),
        @Result(column="INPUTPERSON", property="inputperson", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISONSALE", property="isonsale", jdbcType=JdbcType.CHAR),
        @Result(column="ONSALETIME", property="onsaletime", jdbcType=JdbcType.BIGINT)
    })
    GameInput selectByPrimaryKey(GameInputKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @UpdateProvider(type=GameInputSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GameInput record, @Param("example") GameInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @UpdateProvider(type=GameInputSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GameInput record, @Param("example") GameInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @UpdateProvider(type=GameInputSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GameInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @Update({
        "update t_game_input",
        "set GAMECODE = #{gamecode,jdbcType=VARCHAR},",
          "PRODUCTBATCH = #{productbatch,jdbcType=VARCHAR},",
          "BOOKNUM = #{booknum,jdbcType=VARCHAR},",
          "INPUTTIME = #{inputtime,jdbcType=BIGINT},",
          "INPUTPERSON = #{inputperson,jdbcType=VARCHAR},",
          "ISONSALE = #{isonsale,jdbcType=CHAR},",
          "ONSALETIME = #{onsaletime,jdbcType=BIGINT}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GameInput record);
}