package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.LogMoney;
import com.joyveb.cashmanage.entity.LogMoneyExample;
import com.joyveb.cashmanage.entity.LogMoneyKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface LogMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @SelectProvider(type=LogMoneySqlProvider.class, method="countByExample")
    int countByExample(LogMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @DeleteProvider(type=LogMoneySqlProvider.class, method="deleteByExample")
    int deleteByExample(LogMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @Delete({
        "delete from t_log_money",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(LogMoneyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @Insert({
        "insert into t_log_money (UUID, PARENTNAME, ",
        "ALIPAYNUM, EXTRACTMONEY, ",
        "RESIDUEMONEY, STATUS, ",
        "FAILREASON, EXTRACTTIME, ",
        "DATE)",
        "values (#{uuid,jdbcType=VARCHAR}, #{parentname,jdbcType=VARCHAR}, ",
        "#{alipaynum,jdbcType=VARCHAR}, #{extractmoney,jdbcType=DECIMAL}, ",
        "#{residuemoney,jdbcType=DECIMAL}, #{status,jdbcType=CHAR}, ",
        "#{failreason,jdbcType=VARCHAR}, #{extracttime,jdbcType=BIGINT}, ",
        "#{date,jdbcType=VARCHAR})"
    })
    int insert(LogMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @InsertProvider(type=LogMoneySqlProvider.class, method="insertSelective")
    int insertSelective(LogMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @SelectProvider(type=LogMoneySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="ALIPAYNUM", property="alipaynum", jdbcType= JdbcType.VARCHAR),
        @Result(column="EXTRACTMONEY", property="extractmoney", jdbcType= JdbcType.DECIMAL),
        @Result(column="RESIDUEMONEY", property="residuemoney", jdbcType= JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType= JdbcType.CHAR),
        @Result(column="FAILREASON", property="failreason", jdbcType= JdbcType.VARCHAR),
        @Result(column="EXTRACTTIME", property="extracttime", jdbcType= JdbcType.BIGINT),
        @Result(column="DATE", property="date", jdbcType= JdbcType.VARCHAR)
    })
    List<LogMoney> selectByExample(LogMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @Select({
        "select",
        "UUID, PARENTNAME, ALIPAYNUM, EXTRACTMONEY, RESIDUEMONEY, STATUS, FAILREASON, ",
        "EXTRACTTIME, DATE",
        "from t_log_money",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="ALIPAYNUM", property="alipaynum", jdbcType= JdbcType.VARCHAR),
        @Result(column="EXTRACTMONEY", property="extractmoney", jdbcType= JdbcType.DECIMAL),
        @Result(column="RESIDUEMONEY", property="residuemoney", jdbcType= JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType= JdbcType.CHAR),
        @Result(column="FAILREASON", property="failreason", jdbcType= JdbcType.VARCHAR),
        @Result(column="EXTRACTTIME", property="extracttime", jdbcType= JdbcType.BIGINT),
        @Result(column="DATE", property="date", jdbcType= JdbcType.VARCHAR)
    })
    LogMoney selectByPrimaryKey(LogMoneyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @UpdateProvider(type=LogMoneySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") LogMoney record, @Param("example") LogMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @UpdateProvider(type=LogMoneySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") LogMoney record, @Param("example") LogMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @UpdateProvider(type=LogMoneySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LogMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_money
     *
     * @mbggenerated Sun Aug 20 17:51:59 CST 2017
     */
    @Update({
        "update t_log_money",
        "set PARENTNAME = #{parentname,jdbcType=VARCHAR},",
          "ALIPAYNUM = #{alipaynum,jdbcType=VARCHAR},",
          "EXTRACTMONEY = #{extractmoney,jdbcType=DECIMAL},",
          "RESIDUEMONEY = #{residuemoney,jdbcType=DECIMAL},",
          "STATUS = #{status,jdbcType=CHAR},",
          "FAILREASON = #{failreason,jdbcType=VARCHAR},",
          "EXTRACTTIME = #{extracttime,jdbcType=BIGINT},",
          "DATE = #{date,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(LogMoney record);
}