package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.LogOperter;
import com.joyveb.cashmanage.entity.LogOperterExample;
import com.joyveb.cashmanage.entity.LogOperterKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LogOperterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @SelectProvider(type=LogOperterSqlProvider.class, method="countByExample")
    int countByExample(LogOperterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @DeleteProvider(type=LogOperterSqlProvider.class, method="deleteByExample")
    int deleteByExample(LogOperterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @Delete({
        "delete from t_log_operter",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(LogOperterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @Insert({
        "insert into t_log_operter (UUID, USER_NAME, ",
        "ACTION, OBJECT, ",
        "CONTENT_INFO, OPER_DATE, ",
        "STATUS)",
        "values (#{uuid,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, ",
        "#{action,jdbcType=VARCHAR}, #{object,jdbcType=VARCHAR}, ",
        "#{contentInfo,jdbcType=VARCHAR}, #{operDate,jdbcType=BIGINT}, ",
        "#{status,jdbcType=DECIMAL})"
    })
    int insert(LogOperter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @InsertProvider(type=LogOperterSqlProvider.class, method="insertSelective")
    int insertSelective(LogOperter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @SelectProvider(type=LogOperterSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_NAME", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION", property="action", jdbcType=JdbcType.VARCHAR),
        @Result(column="OBJECT", property="object", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENT_INFO", property="contentInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_DATE", property="operDate", jdbcType=JdbcType.BIGINT),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL)
    })
    List<LogOperter> selectByExample(LogOperterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @Select({
        "select",
        "UUID, USER_NAME, ACTION, OBJECT, CONTENT_INFO, OPER_DATE, STATUS",
        "from t_log_operter",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_NAME", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION", property="action", jdbcType=JdbcType.VARCHAR),
        @Result(column="OBJECT", property="object", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENT_INFO", property="contentInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_DATE", property="operDate", jdbcType=JdbcType.BIGINT),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL)
    })
    LogOperter selectByPrimaryKey(LogOperterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @UpdateProvider(type=LogOperterSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") LogOperter record, @Param("example") LogOperterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @UpdateProvider(type=LogOperterSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") LogOperter record, @Param("example") LogOperterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @UpdateProvider(type=LogOperterSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LogOperter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    @Update({
        "update t_log_operter",
        "set USER_NAME = #{userName,jdbcType=VARCHAR},",
          "ACTION = #{action,jdbcType=VARCHAR},",
          "OBJECT = #{object,jdbcType=VARCHAR},",
          "CONTENT_INFO = #{contentInfo,jdbcType=VARCHAR},",
          "OPER_DATE = #{operDate,jdbcType=BIGINT},",
          "STATUS = #{status,jdbcType=DECIMAL}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(LogOperter record);
}