package com.joyveb.cashmanage.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.joyveb.cashmanage.entity.LogOperter;
import com.joyveb.cashmanage.entity.LogOperterExample.Criteria;
import com.joyveb.cashmanage.entity.LogOperterExample.Criterion;
import com.joyveb.cashmanage.entity.LogOperterExample;
import java.util.List;
import java.util.Map;

public class LogOperterSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    public String countByExample(LogOperterExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("t_log_operter");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    public String deleteByExample(LogOperterExample example) {
        BEGIN();
        DELETE_FROM("t_log_operter");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    public String insertSelective(LogOperter record) {
        BEGIN();
        INSERT_INTO("t_log_operter");
        
        if (record.getUuid() != null) {
            VALUES("UUID", "#{uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            VALUES("USER_NAME", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getAction() != null) {
            VALUES("ACTION", "#{action,jdbcType=VARCHAR}");
        }
        
        if (record.getObject() != null) {
            VALUES("OBJECT", "#{object,jdbcType=VARCHAR}");
        }
        
        if (record.getContentInfo() != null) {
            VALUES("CONTENT_INFO", "#{contentInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getOperDate() != null) {
            VALUES("OPER_DATE", "#{operDate,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            VALUES("STATUS", "#{status,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    public String selectByExample(LogOperterExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("UUID");
        } else {
            SELECT("UUID");
        }
        SELECT("USER_NAME");
        SELECT("ACTION");
        SELECT("OBJECT");
        SELECT("CONTENT_INFO");
        SELECT("OPER_DATE");
        SELECT("STATUS");
        FROM("t_log_operter");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        LogOperter record = (LogOperter) parameter.get("record");
        LogOperterExample example = (LogOperterExample) parameter.get("example");
        
        BEGIN();
        UPDATE("t_log_operter");
        
        if (record.getUuid() != null) {
            SET("UUID = #{record.uuid,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            SET("USER_NAME = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getAction() != null) {
            SET("ACTION = #{record.action,jdbcType=VARCHAR}");
        }
        
        if (record.getObject() != null) {
            SET("OBJECT = #{record.object,jdbcType=VARCHAR}");
        }
        
        if (record.getContentInfo() != null) {
            SET("CONTENT_INFO = #{record.contentInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getOperDate() != null) {
            SET("OPER_DATE = #{record.operDate,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{record.status,jdbcType=DECIMAL}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("t_log_operter");
        
        SET("UUID = #{record.uuid,jdbcType=VARCHAR}");
        SET("USER_NAME = #{record.userName,jdbcType=VARCHAR}");
        SET("ACTION = #{record.action,jdbcType=VARCHAR}");
        SET("OBJECT = #{record.object,jdbcType=VARCHAR}");
        SET("CONTENT_INFO = #{record.contentInfo,jdbcType=VARCHAR}");
        SET("OPER_DATE = #{record.operDate,jdbcType=BIGINT}");
        SET("STATUS = #{record.status,jdbcType=DECIMAL}");
        
        LogOperterExample example = (LogOperterExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    public String updateByPrimaryKeySelective(LogOperter record) {
        BEGIN();
        UPDATE("t_log_operter");
        
        if (record.getUserName() != null) {
            SET("USER_NAME = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getAction() != null) {
            SET("ACTION = #{action,jdbcType=VARCHAR}");
        }
        
        if (record.getObject() != null) {
            SET("OBJECT = #{object,jdbcType=VARCHAR}");
        }
        
        if (record.getContentInfo() != null) {
            SET("CONTENT_INFO = #{contentInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getOperDate() != null) {
            SET("OPER_DATE = #{operDate,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{status,jdbcType=DECIMAL}");
        }
        
        WHERE("UUID = #{uuid,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log_operter
     *
     * @mbggenerated Fri Jun 24 18:33:04 CST 2016
     */
    protected void applyWhere(LogOperterExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}