package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.OrderInfo;
import com.joyveb.cashmanage.entity.OrderInfoExample;
import com.joyveb.cashmanage.entity.OrderInfoKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface OrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @SelectProvider(type=OrderInfoSqlProvider.class, method="countByExample")
    int countByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @DeleteProvider(type=OrderInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Delete({
        "delete from t_order_info",
        "where ORDERID = #{orderid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(OrderInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Insert({
        "insert into t_order_info (ORDERID, ORDERSTATUS, ",
        "DELIVERTIME, FAILREASON, ",
        "LOGISTICSID, WAYBILLNO, ",
        "LOGISTICSSTATUS, LOGISTICSREMARK, ",
        "PAYTIME, USERID, ",
        "PARENTNAME, RECEIVERID, ",
        "ORDERTIME, TOTALAMOUNT, ",
        "FREIGHTPRICE, TAKETIME)",
        "values (#{orderid,jdbcType=VARCHAR}, #{orderstatus,jdbcType=CHAR}, ",
        "#{delivertime,jdbcType=VARCHAR}, #{failreason,jdbcType=VARCHAR}, ",
        "#{logisticsid,jdbcType=VARCHAR}, #{waybillno,jdbcType=VARCHAR}, ",
        "#{logisticsstatus,jdbcType=VARCHAR}, #{logisticsremark,jdbcType=VARCHAR}, ",
        "#{paytime,jdbcType=BIGINT}, #{userid,jdbcType=VARCHAR}, ",
        "#{parentname,jdbcType=VARCHAR}, #{receiverid,jdbcType=VARCHAR}, ",
        "#{ordertime,jdbcType=BIGINT}, #{totalamount,jdbcType=DECIMAL}, ",
        "#{freightprice,jdbcType=DECIMAL}, #{taketime,jdbcType=BIGINT})"
    })
    int insert(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @InsertProvider(type=OrderInfoSqlProvider.class, method="insertSelective")
    int insertSelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @SelectProvider(type=OrderInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ORDERID", property="orderid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="ORDERSTATUS", property="orderstatus", jdbcType= JdbcType.CHAR),
        @Result(column="DELIVERTIME", property="delivertime", jdbcType= JdbcType.VARCHAR),
        @Result(column="FAILREASON", property="failreason", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGISTICSID", property="logisticsid", jdbcType= JdbcType.VARCHAR),
        @Result(column="WAYBILLNO", property="waybillno", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGISTICSSTATUS", property="logisticsstatus", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGISTICSREMARK", property="logisticsremark", jdbcType= JdbcType.VARCHAR),
        @Result(column="PAYTIME", property="paytime", jdbcType= JdbcType.BIGINT),
        @Result(column="USERID", property="userid", jdbcType= JdbcType.VARCHAR),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="RECEIVERID", property="receiverid", jdbcType= JdbcType.VARCHAR),
        @Result(column="ORDERTIME", property="ordertime", jdbcType= JdbcType.BIGINT),
        @Result(column="TOTALAMOUNT", property="totalamount", jdbcType= JdbcType.DECIMAL),
        @Result(column="FREIGHTPRICE", property="freightprice", jdbcType= JdbcType.DECIMAL),
        @Result(column="TAKETIME", property="taketime", jdbcType= JdbcType.BIGINT)
    })
    List<OrderInfo> selectByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Select({
        "select",
        "ORDERID, ORDERSTATUS, DELIVERTIME, FAILREASON, LOGISTICSID, WAYBILLNO, LOGISTICSSTATUS, ",
        "LOGISTICSREMARK, PAYTIME, USERID, PARENTNAME, RECEIVERID, ORDERTIME, TOTALAMOUNT, ",
        "FREIGHTPRICE, TAKETIME",
        "from t_order_info",
        "where ORDERID = #{orderid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORDERID", property="orderid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="ORDERSTATUS", property="orderstatus", jdbcType= JdbcType.CHAR),
        @Result(column="DELIVERTIME", property="delivertime", jdbcType= JdbcType.VARCHAR),
        @Result(column="FAILREASON", property="failreason", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGISTICSID", property="logisticsid", jdbcType= JdbcType.VARCHAR),
        @Result(column="WAYBILLNO", property="waybillno", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGISTICSSTATUS", property="logisticsstatus", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGISTICSREMARK", property="logisticsremark", jdbcType= JdbcType.VARCHAR),
        @Result(column="PAYTIME", property="paytime", jdbcType= JdbcType.BIGINT),
        @Result(column="USERID", property="userid", jdbcType= JdbcType.VARCHAR),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="RECEIVERID", property="receiverid", jdbcType= JdbcType.VARCHAR),
        @Result(column="ORDERTIME", property="ordertime", jdbcType= JdbcType.BIGINT),
        @Result(column="TOTALAMOUNT", property="totalamount", jdbcType= JdbcType.DECIMAL),
        @Result(column="FREIGHTPRICE", property="freightprice", jdbcType= JdbcType.DECIMAL),
        @Result(column="TAKETIME", property="taketime", jdbcType= JdbcType.BIGINT)
    })
    OrderInfo selectByPrimaryKey(OrderInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @UpdateProvider(type=OrderInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @UpdateProvider(type=OrderInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @UpdateProvider(type=OrderInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Update({
        "update t_order_info",
        "set ORDERSTATUS = #{orderstatus,jdbcType=CHAR},",
          "DELIVERTIME = #{delivertime,jdbcType=VARCHAR},",
          "FAILREASON = #{failreason,jdbcType=VARCHAR},",
          "LOGISTICSID = #{logisticsid,jdbcType=VARCHAR},",
          "WAYBILLNO = #{waybillno,jdbcType=VARCHAR},",
          "LOGISTICSSTATUS = #{logisticsstatus,jdbcType=VARCHAR},",
          "LOGISTICSREMARK = #{logisticsremark,jdbcType=VARCHAR},",
          "PAYTIME = #{paytime,jdbcType=BIGINT},",
          "USERID = #{userid,jdbcType=VARCHAR},",
          "PARENTNAME = #{parentname,jdbcType=VARCHAR},",
          "RECEIVERID = #{receiverid,jdbcType=VARCHAR},",
          "ORDERTIME = #{ordertime,jdbcType=BIGINT},",
          "TOTALAMOUNT = #{totalamount,jdbcType=DECIMAL},",
          "FREIGHTPRICE = #{freightprice,jdbcType=DECIMAL},",
          "TAKETIME = #{taketime,jdbcType=BIGINT}",
        "where ORDERID = #{orderid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OrderInfo record);
}