package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.Prizer;
import com.joyveb.cashmanage.entity.PrizerExample;
import com.joyveb.cashmanage.entity.PrizerKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PrizerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @SelectProvider(type=PrizerSqlProvider.class, method="countByExample")
    int countByExample(PrizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @DeleteProvider(type=PrizerSqlProvider.class, method="deleteByExample")
    int deleteByExample(PrizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Delete({
        "delete from t_core_prizer",
        "where MESSAGEID = #{messageid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(PrizerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Insert({
        "insert into t_core_prizer (MESSAGEID, USERID, ",
        "PARENTNAME, DEVICEID, ",
        "BARCODE, AMOUNTSIGN, ",
        "TRANSFERSTATUS, WINAMOUNT, ",
        "REQUESTTIME, TRANSFERTIME)",
        "values (#{messageid,jdbcType=VARCHAR}, #{userid,jdbcType=VARCHAR}, ",
        "#{parentname,jdbcType=VARCHAR}, #{deviceid,jdbcType=VARCHAR}, ",
        "#{barcode,jdbcType=VARCHAR}, #{amountsign,jdbcType=CHAR}, ",
        "#{transferstatus,jdbcType=CHAR}, #{winamount,jdbcType=DECIMAL}, ",
        "#{requesttime,jdbcType=BIGINT}, #{transfertime,jdbcType=BIGINT})"
    })
    int insert(Prizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @InsertProvider(type=PrizerSqlProvider.class, method="insertSelective")
    int insertSelective(Prizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @SelectProvider(type=PrizerSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="MESSAGEID", property="messageid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="USERID", property="userid", jdbcType= JdbcType.VARCHAR),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="DEVICEID", property="deviceid", jdbcType= JdbcType.VARCHAR),
        @Result(column="BARCODE", property="barcode", jdbcType= JdbcType.VARCHAR),
        @Result(column="AMOUNTSIGN", property="amountsign", jdbcType= JdbcType.CHAR),
        @Result(column="TRANSFERSTATUS", property="transferstatus", jdbcType= JdbcType.CHAR),
        @Result(column="WINAMOUNT", property="winamount", jdbcType= JdbcType.DECIMAL),
        @Result(column="REQUESTTIME", property="requesttime", jdbcType= JdbcType.BIGINT),
        @Result(column="TRANSFERTIME", property="transfertime", jdbcType= JdbcType.BIGINT)
    })
    List<Prizer> selectByExample(PrizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Select({
        "select",
        "MESSAGEID, USERID, PARENTNAME, DEVICEID, BARCODE, AMOUNTSIGN, TRANSFERSTATUS, ",
        "WINAMOUNT, REQUESTTIME, TRANSFERTIME",
        "from t_core_prizer",
        "where MESSAGEID = #{messageid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="MESSAGEID", property="messageid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="USERID", property="userid", jdbcType= JdbcType.VARCHAR),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="DEVICEID", property="deviceid", jdbcType= JdbcType.VARCHAR),
        @Result(column="BARCODE", property="barcode", jdbcType= JdbcType.VARCHAR),
        @Result(column="AMOUNTSIGN", property="amountsign", jdbcType= JdbcType.CHAR),
        @Result(column="TRANSFERSTATUS", property="transferstatus", jdbcType= JdbcType.CHAR),
        @Result(column="WINAMOUNT", property="winamount", jdbcType= JdbcType.DECIMAL),
        @Result(column="REQUESTTIME", property="requesttime", jdbcType= JdbcType.BIGINT),
        @Result(column="TRANSFERTIME", property="transfertime", jdbcType= JdbcType.BIGINT)
    })
    Prizer selectByPrimaryKey(PrizerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @UpdateProvider(type=PrizerSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Prizer record, @Param("example") PrizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @UpdateProvider(type=PrizerSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Prizer record, @Param("example") PrizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @UpdateProvider(type=PrizerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Prizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_prizer
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Update({
        "update t_core_prizer",
        "set USERID = #{userid,jdbcType=VARCHAR},",
          "PARENTNAME = #{parentname,jdbcType=VARCHAR},",
          "DEVICEID = #{deviceid,jdbcType=VARCHAR},",
          "BARCODE = #{barcode,jdbcType=VARCHAR},",
          "AMOUNTSIGN = #{amountsign,jdbcType=CHAR},",
          "TRANSFERSTATUS = #{transferstatus,jdbcType=CHAR},",
          "WINAMOUNT = #{winamount,jdbcType=DECIMAL},",
          "REQUESTTIME = #{requesttime,jdbcType=BIGINT},",
          "TRANSFERTIME = #{transfertime,jdbcType=BIGINT}",
        "where MESSAGEID = #{messageid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Prizer record);
}