package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.ReceiverInfo;
import com.joyveb.cashmanage.entity.ReceiverInfoExample;
import com.joyveb.cashmanage.entity.ReceiverInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ReceiverInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @SelectProvider(type=ReceiverInfoSqlProvider.class, method="countByExample")
    int countByExample(ReceiverInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @DeleteProvider(type=ReceiverInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ReceiverInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @Delete({
        "delete from t_receiver_info",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(ReceiverInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @Insert({
        "insert into t_receiver_info (UUID, RECEIVER, ",
        "ADDRESS, PHONE, USERID, ",
        "ISDEFAULT)",
        "values (#{uuid,jdbcType=VARCHAR}, #{receiver,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{phone,jdbcType=BIGINT}, #{userid,jdbcType=VARCHAR}, ",
        "#{isdefault,jdbcType=CHAR})"
    })
    int insert(ReceiverInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @InsertProvider(type=ReceiverInfoSqlProvider.class, method="insertSelective")
    int insertSelective(ReceiverInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @SelectProvider(type=ReceiverInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECEIVER", property="receiver", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="PHONE", property="phone", jdbcType=JdbcType.BIGINT),
        @Result(column="USERID", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISDEFAULT", property="isdefault", jdbcType=JdbcType.CHAR)
    })
    List<ReceiverInfo> selectByExample(ReceiverInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @Select({
        "select",
        "UUID, RECEIVER, ADDRESS, PHONE, USERID, ISDEFAULT",
        "from t_receiver_info",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECEIVER", property="receiver", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="PHONE", property="phone", jdbcType=JdbcType.BIGINT),
        @Result(column="USERID", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISDEFAULT", property="isdefault", jdbcType=JdbcType.CHAR)
    })
    ReceiverInfo selectByPrimaryKey(ReceiverInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @UpdateProvider(type=ReceiverInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ReceiverInfo record, @Param("example") ReceiverInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @UpdateProvider(type=ReceiverInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ReceiverInfo record, @Param("example") ReceiverInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @UpdateProvider(type=ReceiverInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ReceiverInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @Update({
        "update t_receiver_info",
        "set RECEIVER = #{receiver,jdbcType=VARCHAR},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "PHONE = #{phone,jdbcType=BIGINT},",
          "USERID = #{userid,jdbcType=VARCHAR},",
          "ISDEFAULT = #{isdefault,jdbcType=CHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReceiverInfo record);

	/*@SelectProvider(type=ReceiverInfoSqlProvider.class, method="select")
	@Select({
        "select",
        "RECEIVER, ADDRESS, PHONE",
        "from t_receiver_info"
    })
    @Results({
        @Result(column="RECEIVER", property="receiver", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="PHONE", property="phone", jdbcType=JdbcType.BIGINT),
    })
    List<ReceiverInfo> select();*/
}