package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.ShopInfo;
import com.joyveb.cashmanage.entity.ShopInfoExample;
import com.joyveb.cashmanage.entity.ShopInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ShopInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @SelectProvider(type=ShopInfoSqlProvider.class, method="countByExample")
    int countByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @DeleteProvider(type=ShopInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @Delete({
        "delete from t_shop_info",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(ShopInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @Insert({
        "insert into t_shop_info (UUID, ORDERID, ",
        "GAMECODE, ORDERAMOUNT, ",
        "GAMENUM)",
        "values (#{uuid,jdbcType=VARCHAR}, #{orderid,jdbcType=VARCHAR}, ",
        "#{gamecode,jdbcType=VARCHAR}, #{orderamount,jdbcType=DECIMAL}, ",
        "#{gamenum,jdbcType=BIGINT})"
    })
    int insert(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @InsertProvider(type=ShopInfoSqlProvider.class, method="insertSelective")
    int insertSelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @SelectProvider(type=ShopInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORDERID", property="orderid", jdbcType=JdbcType.VARCHAR),
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERAMOUNT", property="orderamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="GAMENUM", property="gamenum", jdbcType=JdbcType.BIGINT)
    })
    List<ShopInfo> selectByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @Select({
        "select",
        "UUID, ORDERID, GAMECODE, ORDERAMOUNT, GAMENUM",
        "from t_shop_info",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORDERID", property="orderid", jdbcType=JdbcType.VARCHAR),
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERAMOUNT", property="orderamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="GAMENUM", property="gamenum", jdbcType=JdbcType.BIGINT)
    })
    ShopInfo selectByPrimaryKey(ShopInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @UpdateProvider(type=ShopInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @UpdateProvider(type=ShopInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @UpdateProvider(type=ShopInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_info
     *
     * @mbggenerated Wed Sep 21 20:12:24 CST 2016
     */
    @Update({
        "update t_shop_info",
        "set ORDERID = #{orderid,jdbcType=VARCHAR},",
          "GAMECODE = #{gamecode,jdbcType=VARCHAR},",
          "ORDERAMOUNT = #{orderamount,jdbcType=DECIMAL},",
          "GAMENUM = #{gamenum,jdbcType=BIGINT}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ShopInfo record);
}