package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.StockManage;
import com.joyveb.cashmanage.entity.StockManageExample;
import com.joyveb.cashmanage.entity.StockManageKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface StockManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @SelectProvider(type=StockManageSqlProvider.class, method="countByExample")
    int countByExample(StockManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @DeleteProvider(type=StockManageSqlProvider.class, method="deleteByExample")
    int deleteByExample(StockManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @Delete({
        "delete from t_stock_manage",
        "where GAMECODE = #{gamecode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(StockManageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @Insert({
        "insert into t_stock_manage (GAMECODE, TOTAL, ",
        "UPDATETIME)",
        "values (#{gamecode,jdbcType=VARCHAR}, #{total,jdbcType=BIGINT}, ",
        "#{updatetime,jdbcType=BIGINT})"
    })
    int insert(StockManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @InsertProvider(type=StockManageSqlProvider.class, method="insertSelective")
    int insertSelective(StockManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @SelectProvider(type=StockManageSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TOTAL", property="total", jdbcType=JdbcType.BIGINT),
        @Result(column="UPDATETIME", property="updatetime", jdbcType=JdbcType.BIGINT)
    })
    List<StockManage> selectByExample(StockManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @Select({
        "select",
        "GAMECODE, TOTAL, UPDATETIME",
        "from t_stock_manage",
        "where GAMECODE = #{gamecode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="GAMECODE", property="gamecode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TOTAL", property="total", jdbcType=JdbcType.BIGINT),
        @Result(column="UPDATETIME", property="updatetime", jdbcType=JdbcType.BIGINT)
    })
    StockManage selectByPrimaryKey(StockManageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @UpdateProvider(type=StockManageSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") StockManage record, @Param("example") StockManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @UpdateProvider(type=StockManageSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") StockManage record, @Param("example") StockManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @UpdateProvider(type=StockManageSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(StockManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @Update({
        "update t_stock_manage",
        "set TOTAL = #{total,jdbcType=BIGINT},",
          "UPDATETIME = #{updatetime,jdbcType=BIGINT}",
        "where GAMECODE = #{gamecode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(StockManage record);
}