package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.Terminal;
import com.joyveb.cashmanage.entity.TerminalExample;
import com.joyveb.cashmanage.entity.TerminalKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @SelectProvider(type=TerminalSqlProvider.class, method="countByExample")
    int countByExample(TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @DeleteProvider(type=TerminalSqlProvider.class, method="deleteByExample")
    int deleteByExample(TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @Delete({
        "delete from t_ips_terminal",
        "where SESSIONID = #{sessionid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TerminalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @Insert({
        "insert into t_ips_terminal (SESSIONID, ISUSED)",
        "values (#{sessionid,jdbcType=VARCHAR}, #{isused,jdbcType=CHAR})"
    })
    int insert(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @InsertProvider(type=TerminalSqlProvider.class, method="insertSelective")
    int insertSelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @SelectProvider(type=TerminalSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="SESSIONID", property="sessionid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ISUSED", property="isused", jdbcType=JdbcType.CHAR)
    })
    List<Terminal> selectByExample(TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @Select({
        "select",
        "SESSIONID, ISUSED",
        "from t_ips_terminal",
        "where SESSIONID = #{sessionid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="SESSIONID", property="sessionid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ISUSED", property="isused", jdbcType=JdbcType.CHAR)
    })
    Terminal selectByPrimaryKey(TerminalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @UpdateProvider(type=TerminalSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Terminal record, @Param("example") TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @UpdateProvider(type=TerminalSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Terminal record, @Param("example") TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @UpdateProvider(type=TerminalSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @Update({
        "update t_ips_terminal",
        "set ISUSED = #{isused,jdbcType=CHAR}",
        "where SESSIONID = #{sessionid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Terminal record);
}