package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.TransferRecord;
import com.joyveb.cashmanage.entity.TransferRecordExample;
import com.joyveb.cashmanage.entity.TransferRecordKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TransferRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @SelectProvider(type=TransferRecordSqlProvider.class, method="countByExample")
    int countByExample(TransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @DeleteProvider(type=TransferRecordSqlProvider.class, method="deleteByExample")
    int deleteByExample(TransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @Delete({
        "delete from t_acc_transferrecord",
        "where OUTTRADENUM = #{outtradenum,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TransferRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @Insert({
        "insert into t_acc_transferrecord (OUTTRADENUM, TRANSFERTYPE, ",
        "TRANSFEROUT, TRANSFERIN, ",
        "TRANSFERAMOUNT, FACTORAGE, ",
        "STATUS, TRADENUM, MESSAGEIDS, ",
        "TRANSFERTIME, FAILREASON)",
        "values (#{outtradenum,jdbcType=VARCHAR}, #{transfertype,jdbcType=CHAR}, ",
        "#{transferout,jdbcType=VARCHAR}, #{transferin,jdbcType=VARCHAR}, ",
        "#{transferamount,jdbcType=DECIMAL}, #{factorage,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=CHAR}, #{tradenum,jdbcType=VARCHAR}, #{messageids,jdbcType=VARCHAR}, ",
        "#{transfertime,jdbcType=BIGINT}, #{failreason,jdbcType=VARCHAR})"
    })
    int insert(TransferRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @InsertProvider(type=TransferRecordSqlProvider.class, method="insertSelective")
    int insertSelective(TransferRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @SelectProvider(type=TransferRecordSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="OUTTRADENUM", property="outtradenum", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TRANSFERTYPE", property="transfertype", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSFEROUT", property="transferout", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFERIN", property="transferin", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFERAMOUNT", property="transferamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="FACTORAGE", property="factorage", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="TRADENUM", property="tradenum", jdbcType=JdbcType.VARCHAR),
        @Result(column="MESSAGEIDS", property="messageids", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFERTIME", property="transfertime", jdbcType=JdbcType.BIGINT),
        @Result(column="FAILREASON", property="failreason", jdbcType=JdbcType.VARCHAR)
    })
    List<TransferRecord> selectByExample(TransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @Select({
        "select",
        "OUTTRADENUM, TRANSFERTYPE, TRANSFEROUT, TRANSFERIN, TRANSFERAMOUNT, FACTORAGE, ",
        "STATUS, TRADENUM, MESSAGEIDS, TRANSFERTIME, FAILREASON",
        "from t_acc_transferrecord",
        "where OUTTRADENUM = #{outtradenum,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="OUTTRADENUM", property="outtradenum", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TRANSFERTYPE", property="transfertype", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSFEROUT", property="transferout", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFERIN", property="transferin", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFERAMOUNT", property="transferamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="FACTORAGE", property="factorage", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="TRADENUM", property="tradenum", jdbcType=JdbcType.VARCHAR),
        @Result(column="MESSAGEIDS", property="messageids", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFERTIME", property="transfertime", jdbcType=JdbcType.BIGINT),
        @Result(column="FAILREASON", property="failreason", jdbcType=JdbcType.VARCHAR)
    })
    TransferRecord selectByPrimaryKey(TransferRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @UpdateProvider(type=TransferRecordSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TransferRecord record, @Param("example") TransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @UpdateProvider(type=TransferRecordSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TransferRecord record, @Param("example") TransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @UpdateProvider(type=TransferRecordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TransferRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    @Update({
        "update t_acc_transferrecord",
        "set TRANSFERTYPE = #{transfertype,jdbcType=CHAR},",
          "TRANSFEROUT = #{transferout,jdbcType=VARCHAR},",
          "TRANSFERIN = #{transferin,jdbcType=VARCHAR},",
          "TRANSFERAMOUNT = #{transferamount,jdbcType=DECIMAL},",
          "FACTORAGE = #{factorage,jdbcType=DECIMAL},",
          "STATUS = #{status,jdbcType=CHAR},",
          "TRADENUM = #{tradenum,jdbcType=VARCHAR},",
          "MESSAGEIDS = #{messageids,jdbcType=VARCHAR},",
          "TRANSFERTIME = #{transfertime,jdbcType=BIGINT},",
          "FAILREASON = #{failreason,jdbcType=VARCHAR}",
        "where OUTTRADENUM = #{outtradenum,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TransferRecord record);
}