package com.joyveb.cashmanage.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.joyveb.cashmanage.entity.Version;
import com.joyveb.cashmanage.entity.VersionExample.Criteria;
import com.joyveb.cashmanage.entity.VersionExample.Criterion;
import com.joyveb.cashmanage.entity.VersionExample;
import java.util.List;
import java.util.Map;

public class VersionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    public String countByExample(VersionExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("t_app_version");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    public String deleteByExample(VersionExample example) {
        BEGIN();
        DELETE_FROM("t_app_version");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    public String insertSelective(Version record) {
        BEGIN();
        INSERT_INTO("t_app_version");
        
        if (record.getVol() != null) {
            VALUES("VOL", "#{vol,jdbcType=INTEGER}");
        }
        
        if (record.getVersion() != null) {
            VALUES("VERSION", "#{version,jdbcType=VARCHAR}");
        }
        
        if (record.getPubtime() != null) {
            VALUES("PUBTIME", "#{pubtime,jdbcType=BIGINT}");
        }
        
        if (record.getUrl() != null) {
            VALUES("URL", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            VALUES("COMMENT", "#{comment,jdbcType=VARCHAR}");
        }
        
        if (record.getApkpath() != null) {
            VALUES("APKPATH", "#{apkpath,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    public String selectByExample(VersionExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("VOL");
        } else {
            SELECT("VOL");
        }
        SELECT("VERSION");
        SELECT("PUBTIME");
        SELECT("URL");
        SELECT("COMMENT");
        SELECT("APKPATH");
        FROM("t_app_version");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Version record = (Version) parameter.get("record");
        VersionExample example = (VersionExample) parameter.get("example");
        
        BEGIN();
        UPDATE("t_app_version");
        
        if (record.getVol() != null) {
            SET("VOL = #{record.vol,jdbcType=INTEGER}");
        }
        
        if (record.getVersion() != null) {
            SET("VERSION = #{record.version,jdbcType=VARCHAR}");
        }
        
        if (record.getPubtime() != null) {
            SET("PUBTIME = #{record.pubtime,jdbcType=BIGINT}");
        }
        
        if (record.getUrl() != null) {
            SET("URL = #{record.url,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            SET("COMMENT = #{record.comment,jdbcType=VARCHAR}");
        }
        
        if (record.getApkpath() != null) {
            SET("APKPATH = #{record.apkpath,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("t_app_version");
        
        SET("VOL = #{record.vol,jdbcType=INTEGER}");
        SET("VERSION = #{record.version,jdbcType=VARCHAR}");
        SET("PUBTIME = #{record.pubtime,jdbcType=BIGINT}");
        SET("URL = #{record.url,jdbcType=VARCHAR}");
        SET("COMMENT = #{record.comment,jdbcType=VARCHAR}");
        SET("APKPATH = #{record.apkpath,jdbcType=VARCHAR}");
        
        VersionExample example = (VersionExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    public String updateByPrimaryKeySelective(Version record) {
        BEGIN();
        UPDATE("t_app_version");
        
        if (record.getVersion() != null) {
            SET("VERSION = #{version,jdbcType=VARCHAR}");
        }
        
        if (record.getPubtime() != null) {
            SET("PUBTIME = #{pubtime,jdbcType=BIGINT}");
        }
        
        if (record.getUrl() != null) {
            SET("URL = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getComment() != null) {
            SET("COMMENT = #{comment,jdbcType=VARCHAR}");
        }
        
        if (record.getApkpath() != null) {
            SET("APKPATH = #{apkpath,jdbcType=VARCHAR}");
        }
        
        WHERE("VOL = #{vol,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    protected void applyWhere(VersionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}