package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.Version;
import com.joyveb.cashmanage.entity.VersionExample;
import com.joyveb.cashmanage.entity.VersionKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface VersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @SelectProvider(type=VersionSqlProvider.class, method="countByExample")
    int countByExample(VersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @DeleteProvider(type=VersionSqlProvider.class, method="deleteByExample")
    int deleteByExample(VersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @Delete({
        "delete from t_app_version",
        "where VOL = #{vol,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(VersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @Insert({
        "insert into t_app_version (VOL, VERSION, ",
        "PUBTIME, URL, COMMENT, ",
        "APKPATH)",
        "values (#{vol,jdbcType=INTEGER}, #{version,jdbcType=VARCHAR}, ",
        "#{pubtime,jdbcType=BIGINT}, #{url,jdbcType=VARCHAR}, #{comment,jdbcType=VARCHAR}, ",
        "#{apkpath,jdbcType=VARCHAR})"
    })
    int insert(Version record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @InsertProvider(type=VersionSqlProvider.class, method="insertSelective")
    int insertSelective(Version record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @SelectProvider(type=VersionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="VOL", property="vol", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.VARCHAR),
        @Result(column="PUBTIME", property="pubtime", jdbcType=JdbcType.BIGINT),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENT", property="comment", jdbcType=JdbcType.VARCHAR),
        @Result(column="APKPATH", property="apkpath", jdbcType=JdbcType.VARCHAR)
    })
    List<Version> selectByExample(VersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @Select({
        "select",
        "VOL, VERSION, PUBTIME, URL, COMMENT, APKPATH",
        "from t_app_version",
        "where VOL = #{vol,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="VOL", property="vol", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.VARCHAR),
        @Result(column="PUBTIME", property="pubtime", jdbcType=JdbcType.BIGINT),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENT", property="comment", jdbcType=JdbcType.VARCHAR),
        @Result(column="APKPATH", property="apkpath", jdbcType=JdbcType.VARCHAR)
    })
    Version selectByPrimaryKey(VersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @UpdateProvider(type=VersionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Version record, @Param("example") VersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @UpdateProvider(type=VersionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Version record, @Param("example") VersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @UpdateProvider(type=VersionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Version record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_version
     *
     * @mbggenerated Tue Mar 14 10:59:33 CST 2017
     */
    @Update({
        "update t_app_version",
        "set VERSION = #{version,jdbcType=VARCHAR},",
          "PUBTIME = #{pubtime,jdbcType=BIGINT},",
          "URL = #{url,jdbcType=VARCHAR},",
          "COMMENT = #{comment,jdbcType=VARCHAR},",
          "APKPATH = #{apkpath,jdbcType=VARCHAR}",
        "where VOL = #{vol,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Version record);
}