package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.WhiteList;
import com.joyveb.cashmanage.entity.WhiteListExample;
import com.joyveb.cashmanage.entity.WhiteListKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface WhiteListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @SelectProvider(type=WhiteListSqlProvider.class, method="countByExample")
    int countByExample(WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @DeleteProvider(type=WhiteListSqlProvider.class, method="deleteByExample")
    int deleteByExample(WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @Delete({
        "delete from t_acc_whitelist",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(WhiteListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @Insert({
        "insert into t_acc_whitelist (UUID, FULLNAME, ",
        "IDCARD, MOBILE, ",
        "ADDRESS, TRANSFERCYCLE, ",
        "USERID, STATUS, USERKEY, ",
        "COMMENT, USETIME, ",
        "DEPOSIT, DEVICETYPE, ",
        "DEVICENUM, COMMISSION, ",
        "PARENTNAME, USERNAME, ",
        "PASSWORD, ALIPAYNUM, ",
        "LOGINTIME)",
        "values (#{uuid,jdbcType=VARCHAR}, #{fullname,jdbcType=VARCHAR}, ",
        "#{idcard,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{transfercycle,jdbcType=INTEGER}, ",
        "#{userid,jdbcType=VARCHAR}, #{status,jdbcType=CHAR}, #{userkey,jdbcType=VARCHAR}, ",
        "#{comment,jdbcType=VARCHAR}, #{usetime,jdbcType=BIGINT}, ",
        "#{deposit,jdbcType=BIGINT}, #{devicetype,jdbcType=VARCHAR}, ",
        "#{devicenum,jdbcType=VARCHAR}, #{commission,jdbcType=VARCHAR}, ",
        "#{parentname,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{alipaynum,jdbcType=VARCHAR}, ",
        "#{logintime,jdbcType=BIGINT})"
    })
    int insert(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @InsertProvider(type=WhiteListSqlProvider.class, method="insertSelective")
    int insertSelective(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @SelectProvider(type=WhiteListSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="FULLNAME", property="fullname", jdbcType= JdbcType.VARCHAR),
        @Result(column="IDCARD", property="idcard", jdbcType= JdbcType.VARCHAR),
        @Result(column="MOBILE", property="mobile", jdbcType= JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType= JdbcType.VARCHAR),
        @Result(column="TRANSFERCYCLE", property="transfercycle", jdbcType= JdbcType.INTEGER),
        @Result(column="USERID", property="userid", jdbcType= JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType= JdbcType.CHAR),
        @Result(column="USERKEY", property="userkey", jdbcType= JdbcType.VARCHAR),
        @Result(column="COMMENT", property="comment", jdbcType= JdbcType.VARCHAR),
        @Result(column="USETIME", property="usetime", jdbcType= JdbcType.BIGINT),
        @Result(column="DEPOSIT", property="deposit", jdbcType= JdbcType.BIGINT),
        @Result(column="DEVICETYPE", property="devicetype", jdbcType= JdbcType.VARCHAR),
        @Result(column="DEVICENUM", property="devicenum", jdbcType= JdbcType.VARCHAR),
        @Result(column="COMMISSION", property="commission", jdbcType= JdbcType.VARCHAR),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="USERNAME", property="username", jdbcType= JdbcType.VARCHAR),
        @Result(column="PASSWORD", property="password", jdbcType= JdbcType.VARCHAR),
        @Result(column="ALIPAYNUM", property="alipaynum", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGINTIME", property="logintime", jdbcType= JdbcType.BIGINT)
    })
    List<WhiteList> selectByExample(WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @Select({
        "select",
        "UUID, FULLNAME, IDCARD, MOBILE, ADDRESS, TRANSFERCYCLE, USERID, STATUS, USERKEY, ",
        "COMMENT, USETIME, DEPOSIT, DEVICETYPE, DEVICENUM, COMMISSION, PARENTNAME, USERNAME, ",
        "PASSWORD, ALIPAYNUM, LOGINTIME",
        "from t_acc_whitelist",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType= JdbcType.VARCHAR, id=true),
        @Result(column="FULLNAME", property="fullname", jdbcType= JdbcType.VARCHAR),
        @Result(column="IDCARD", property="idcard", jdbcType= JdbcType.VARCHAR),
        @Result(column="MOBILE", property="mobile", jdbcType= JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType= JdbcType.VARCHAR),
        @Result(column="TRANSFERCYCLE", property="transfercycle", jdbcType= JdbcType.INTEGER),
        @Result(column="USERID", property="userid", jdbcType= JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType= JdbcType.CHAR),
        @Result(column="USERKEY", property="userkey", jdbcType= JdbcType.VARCHAR),
        @Result(column="COMMENT", property="comment", jdbcType= JdbcType.VARCHAR),
        @Result(column="USETIME", property="usetime", jdbcType= JdbcType.BIGINT),
        @Result(column="DEPOSIT", property="deposit", jdbcType= JdbcType.BIGINT),
        @Result(column="DEVICETYPE", property="devicetype", jdbcType= JdbcType.VARCHAR),
        @Result(column="DEVICENUM", property="devicenum", jdbcType= JdbcType.VARCHAR),
        @Result(column="COMMISSION", property="commission", jdbcType= JdbcType.VARCHAR),
        @Result(column="PARENTNAME", property="parentname", jdbcType= JdbcType.VARCHAR),
        @Result(column="USERNAME", property="username", jdbcType= JdbcType.VARCHAR),
        @Result(column="PASSWORD", property="password", jdbcType= JdbcType.VARCHAR),
        @Result(column="ALIPAYNUM", property="alipaynum", jdbcType= JdbcType.VARCHAR),
        @Result(column="LOGINTIME", property="logintime", jdbcType= JdbcType.BIGINT)
    })
    WhiteList selectByPrimaryKey(WhiteListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @UpdateProvider(type=WhiteListSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WhiteList record, @Param("example") WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @UpdateProvider(type=WhiteListSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WhiteList record, @Param("example") WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @UpdateProvider(type=WhiteListSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitelist
     *
     * @mbggenerated Thu Aug 17 17:56:38 CST 2017
     */
    @Update({
        "update t_acc_whitelist",
        "set FULLNAME = #{fullname,jdbcType=VARCHAR},",
          "IDCARD = #{idcard,jdbcType=VARCHAR},",
          "MOBILE = #{mobile,jdbcType=VARCHAR},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "TRANSFERCYCLE = #{transfercycle,jdbcType=INTEGER},",
          "USERID = #{userid,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=CHAR},",
          "USERKEY = #{userkey,jdbcType=VARCHAR},",
          "COMMENT = #{comment,jdbcType=VARCHAR},",
          "USETIME = #{usetime,jdbcType=BIGINT},",
          "DEPOSIT = #{deposit,jdbcType=BIGINT},",
          "DEVICETYPE = #{devicetype,jdbcType=VARCHAR},",
          "DEVICENUM = #{devicenum,jdbcType=VARCHAR},",
          "COMMISSION = #{commission,jdbcType=VARCHAR},",
          "PARENTNAME = #{parentname,jdbcType=VARCHAR},",
          "USERNAME = #{username,jdbcType=VARCHAR},",
          "PASSWORD = #{password,jdbcType=VARCHAR},",
          "ALIPAYNUM = #{alipaynum,jdbcType=VARCHAR},",
          "LOGINTIME = #{logintime,jdbcType=BIGINT}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WhiteList record);
}