package com.joyveb.cashmanage.mapper;

import com.joyveb.cashmanage.entity.WhiteChild;
import com.joyveb.cashmanage.entity.WhiteChildExample;
import com.joyveb.cashmanage.entity.WhiteChildKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WhiteChildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @SelectProvider(type=WhiteChildSqlProvider.class, method="countByExample")
    int countByExample(WhiteChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @DeleteProvider(type=WhiteChildSqlProvider.class, method="deleteByExample")
    int deleteByExample(WhiteChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @Delete({
        "delete from t_acc_whitechild",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(WhiteChildKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @Insert({
        "insert into t_acc_whitechild (UUID, USERNAME, ",
        "PASSWORD, PARENTID, ",
        "DEVICETYPE, DEVICENUM)",
        "values (#{uuid,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{parentid,jdbcType=VARCHAR}, ",
        "#{devicetype,jdbcType=VARCHAR}, #{devicenum,jdbcType=VARCHAR})"
    })
    int insert(WhiteChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @InsertProvider(type=WhiteChildSqlProvider.class, method="insertSelective")
    int insertSelective(WhiteChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @SelectProvider(type=WhiteChildSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USERNAME", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="PASSWORD", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="PARENTID", property="parentid", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEVICETYPE", property="devicetype", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEVICENUM", property="devicenum", jdbcType=JdbcType.VARCHAR)
    })
    List<WhiteChild> selectByExample(WhiteChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @Select({
        "select",
        "UUID, USERNAME, PASSWORD, PARENTID, DEVICETYPE, DEVICENUM",
        "from t_acc_whitechild",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UUID", property="uuid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USERNAME", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="PASSWORD", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="PARENTID", property="parentid", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEVICETYPE", property="devicetype", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEVICENUM", property="devicenum", jdbcType=JdbcType.VARCHAR)
    })
    WhiteChild selectByPrimaryKey(WhiteChildKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @UpdateProvider(type=WhiteChildSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WhiteChild record, @Param("example") WhiteChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @UpdateProvider(type=WhiteChildSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WhiteChild record, @Param("example") WhiteChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @UpdateProvider(type=WhiteChildSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WhiteChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_whitechild
     *
     * @mbggenerated Fri Mar 10 15:34:18 CST 2017
     */
    @Update({
        "update t_acc_whitechild",
        "set USERNAME = #{username,jdbcType=VARCHAR},",
          "PASSWORD = #{password,jdbcType=VARCHAR},",
          "PARENTID = #{parentid,jdbcType=VARCHAR},",
          "DEVICETYPE = #{devicetype,jdbcType=VARCHAR},",
          "DEVICENUM = #{devicenum,jdbcType=VARCHAR}",
        "where UUID = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WhiteChild record);
}