package com.joyveb.cashmanage.entity;

public class DbPropertiesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manage_dbproperties.THEKEY
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    private String thekey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manage_dbproperties.THEKEY
     *
     * @return the value of t_manage_dbproperties.THEKEY
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    public String getThekey() {
        return thekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manage_dbproperties.THEKEY
     *
     * @param thekey the value for t_manage_dbproperties.THEKEY
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    public void setThekey(String thekey) {
        this.thekey = thekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbPropertiesKey other = (DbPropertiesKey) that;
        return (this.getThekey() == null ? other.getThekey() == null : this.getThekey().equals(other.getThekey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getThekey() == null) ? 0 : getThekey().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_dbproperties
     *
     * @mbggenerated Mon Jun 13 15:52:04 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", thekey=").append(thekey);
        sb.append("]");
        return sb.toString();
    }
}