package com.joyveb.cashmanage.entity;

public class GameInput extends GameInputKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_input.GAMECODE
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    private String gamecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_input.PRODUCTBATCH
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    private String productbatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_input.BOOKNUM
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    private String booknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_input.INPUTTIME
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    private Long inputtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_input.INPUTPERSON
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    private String inputperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_input.ISONSALE
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    private String isonsale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_input.ONSALETIME
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    private Long onsaletime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_input.GAMECODE
     *
     * @return the value of t_game_input.GAMECODE
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public String getGamecode() {
        return gamecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_input.GAMECODE
     *
     * @param gamecode the value for t_game_input.GAMECODE
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public void setGamecode(String gamecode) {
        this.gamecode = gamecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_input.PRODUCTBATCH
     *
     * @return the value of t_game_input.PRODUCTBATCH
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public String getProductbatch() {
        return productbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_input.PRODUCTBATCH
     *
     * @param productbatch the value for t_game_input.PRODUCTBATCH
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public void setProductbatch(String productbatch) {
        this.productbatch = productbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_input.BOOKNUM
     *
     * @return the value of t_game_input.BOOKNUM
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public String getBooknum() {
        return booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_input.BOOKNUM
     *
     * @param booknum the value for t_game_input.BOOKNUM
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public void setBooknum(String booknum) {
        this.booknum = booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_input.INPUTTIME
     *
     * @return the value of t_game_input.INPUTTIME
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public Long getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_input.INPUTTIME
     *
     * @param inputtime the value for t_game_input.INPUTTIME
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public void setInputtime(Long inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_input.INPUTPERSON
     *
     * @return the value of t_game_input.INPUTPERSON
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public String getInputperson() {
        return inputperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_input.INPUTPERSON
     *
     * @param inputperson the value for t_game_input.INPUTPERSON
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public void setInputperson(String inputperson) {
        this.inputperson = inputperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_input.ISONSALE
     *
     * @return the value of t_game_input.ISONSALE
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public String getIsonsale() {
        return isonsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_input.ISONSALE
     *
     * @param isonsale the value for t_game_input.ISONSALE
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public void setIsonsale(String isonsale) {
        this.isonsale = isonsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_input.ONSALETIME
     *
     * @return the value of t_game_input.ONSALETIME
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public Long getOnsaletime() {
        return onsaletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_input.ONSALETIME
     *
     * @param onsaletime the value for t_game_input.ONSALETIME
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    public void setOnsaletime(Long onsaletime) {
        this.onsaletime = onsaletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GameInput other = (GameInput) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getGamecode() == null ? other.getGamecode() == null : this.getGamecode().equals(other.getGamecode()))
            && (this.getProductbatch() == null ? other.getProductbatch() == null : this.getProductbatch().equals(other.getProductbatch()))
            && (this.getBooknum() == null ? other.getBooknum() == null : this.getBooknum().equals(other.getBooknum()))
            && (this.getInputtime() == null ? other.getInputtime() == null : this.getInputtime().equals(other.getInputtime()))
            && (this.getInputperson() == null ? other.getInputperson() == null : this.getInputperson().equals(other.getInputperson()))
            && (this.getIsonsale() == null ? other.getIsonsale() == null : this.getIsonsale().equals(other.getIsonsale()))
            && (this.getOnsaletime() == null ? other.getOnsaletime() == null : this.getOnsaletime().equals(other.getOnsaletime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getGamecode() == null) ? 0 : getGamecode().hashCode());
        result = prime * result + ((getProductbatch() == null) ? 0 : getProductbatch().hashCode());
        result = prime * result + ((getBooknum() == null) ? 0 : getBooknum().hashCode());
        result = prime * result + ((getInputtime() == null) ? 0 : getInputtime().hashCode());
        result = prime * result + ((getInputperson() == null) ? 0 : getInputperson().hashCode());
        result = prime * result + ((getIsonsale() == null) ? 0 : getIsonsale().hashCode());
        result = prime * result + ((getOnsaletime() == null) ? 0 : getOnsaletime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_input
     *
     * @mbggenerated Mon Mar 13 11:43:43 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gamecode=").append(gamecode);
        sb.append(", productbatch=").append(productbatch);
        sb.append(", booknum=").append(booknum);
        sb.append(", inputtime=").append(inputtime);
        sb.append(", inputperson=").append(inputperson);
        sb.append(", isonsale=").append(isonsale);
        sb.append(", onsaletime=").append(onsaletime);
        sb.append("]");
        return sb.toString();
    }
}