package com.joyveb.cashmanage.entity;

public class GameOut extends GameOutKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_out.GAMECODE
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    private String gamecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_out.PRODUCTBATCH
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    private String productbatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_out.BOOKNUM
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    private String booknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_out.OUTTIME
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    private Long outtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_out.OUTPERSON
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    private String outperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_game_out.ORDERID
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    private String orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_out.GAMECODE
     *
     * @return the value of t_game_out.GAMECODE
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public String getGamecode() {
        return gamecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_out.GAMECODE
     *
     * @param gamecode the value for t_game_out.GAMECODE
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public void setGamecode(String gamecode) {
        this.gamecode = gamecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_out.PRODUCTBATCH
     *
     * @return the value of t_game_out.PRODUCTBATCH
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public String getProductbatch() {
        return productbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_out.PRODUCTBATCH
     *
     * @param productbatch the value for t_game_out.PRODUCTBATCH
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public void setProductbatch(String productbatch) {
        this.productbatch = productbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_out.BOOKNUM
     *
     * @return the value of t_game_out.BOOKNUM
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public String getBooknum() {
        return booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_out.BOOKNUM
     *
     * @param booknum the value for t_game_out.BOOKNUM
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public void setBooknum(String booknum) {
        this.booknum = booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_out.OUTTIME
     *
     * @return the value of t_game_out.OUTTIME
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public Long getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_out.OUTTIME
     *
     * @param outtime the value for t_game_out.OUTTIME
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public void setOuttime(Long outtime) {
        this.outtime = outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_out.OUTPERSON
     *
     * @return the value of t_game_out.OUTPERSON
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public String getOutperson() {
        return outperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_out.OUTPERSON
     *
     * @param outperson the value for t_game_out.OUTPERSON
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public void setOutperson(String outperson) {
        this.outperson = outperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_game_out.ORDERID
     *
     * @return the value of t_game_out.ORDERID
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_game_out.ORDERID
     *
     * @param orderid the value for t_game_out.ORDERID
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GameOut other = (GameOut) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getGamecode() == null ? other.getGamecode() == null : this.getGamecode().equals(other.getGamecode()))
            && (this.getProductbatch() == null ? other.getProductbatch() == null : this.getProductbatch().equals(other.getProductbatch()))
            && (this.getBooknum() == null ? other.getBooknum() == null : this.getBooknum().equals(other.getBooknum()))
            && (this.getOuttime() == null ? other.getOuttime() == null : this.getOuttime().equals(other.getOuttime()))
            && (this.getOutperson() == null ? other.getOutperson() == null : this.getOutperson().equals(other.getOutperson()))
            && (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getGamecode() == null) ? 0 : getGamecode().hashCode());
        result = prime * result + ((getProductbatch() == null) ? 0 : getProductbatch().hashCode());
        result = prime * result + ((getBooknum() == null) ? 0 : getBooknum().hashCode());
        result = prime * result + ((getOuttime() == null) ? 0 : getOuttime().hashCode());
        result = prime * result + ((getOutperson() == null) ? 0 : getOutperson().hashCode());
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_out
     *
     * @mbggenerated Mon Mar 13 14:58:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gamecode=").append(gamecode);
        sb.append(", productbatch=").append(productbatch);
        sb.append(", booknum=").append(booknum);
        sb.append(", outtime=").append(outtime);
        sb.append(", outperson=").append(outperson);
        sb.append(", orderid=").append(orderid);
        sb.append("]");
        return sb.toString();
    }
}