package com.joyveb.cashmanage.entity;

import java.util.ArrayList;
import java.util.List;

public class OrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    *
    * @generated Mon Aug 34 20:00:28 CST 2017
    */
    protected int offset;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    *
    * @generated Mon Aug 34 20:00:28 CST 2017
    */
    protected int limit;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    protected String sumCol;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    protected String groupSelClause;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public OrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    *
    * @generated Mon Aug 34 20:00:28 CST 2017
    */
    public void setOffset(int offset) {
         this.offset = offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    *
    * @generated Mon Aug 34 20:00:28 CST 2017
    */
    public int getOffset() {
          return offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    *
    * @generated Mon Aug 34 20:00:28 CST 2017
    */
    public void setLimit(int limit) {
         this.limit = limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    *
    * @generated Mon Aug 34 20:00:28 CST 2017
    */
    public int getLimit() {
          return limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    public String getSumCol() {
          return sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    public String getGroupSelClause() {
          return groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_order_info
    */
    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderidIsNull() {
            addCriterion("ORDERID is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("ORDERID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("ORDERID =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("ORDERID <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("ORDERID >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("ORDERID >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("ORDERID <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("ORDERID <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("ORDERID like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("ORDERID not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("ORDERID in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("ORDERID not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("ORDERID between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("ORDERID not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNull() {
            addCriterion("ORDERSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNotNull() {
            addCriterion("ORDERSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusEqualTo(String value) {
            addCriterion("ORDERSTATUS =", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotEqualTo(String value) {
            addCriterion("ORDERSTATUS <>", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThan(String value) {
            addCriterion("ORDERSTATUS >", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThanOrEqualTo(String value) {
            addCriterion("ORDERSTATUS >=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThan(String value) {
            addCriterion("ORDERSTATUS <", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThanOrEqualTo(String value) {
            addCriterion("ORDERSTATUS <=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLike(String value) {
            addCriterion("ORDERSTATUS like", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotLike(String value) {
            addCriterion("ORDERSTATUS not like", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIn(List<String> values) {
            addCriterion("ORDERSTATUS in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotIn(List<String> values) {
            addCriterion("ORDERSTATUS not in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusBetween(String value1, String value2) {
            addCriterion("ORDERSTATUS between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotBetween(String value1, String value2) {
            addCriterion("ORDERSTATUS not between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andDelivertimeIsNull() {
            addCriterion("DELIVERTIME is null");
            return (Criteria) this;
        }

        public Criteria andDelivertimeIsNotNull() {
            addCriterion("DELIVERTIME is not null");
            return (Criteria) this;
        }

        public Criteria andDelivertimeEqualTo(String value) {
            addCriterion("DELIVERTIME =", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeNotEqualTo(String value) {
            addCriterion("DELIVERTIME <>", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeGreaterThan(String value) {
            addCriterion("DELIVERTIME >", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERTIME >=", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeLessThan(String value) {
            addCriterion("DELIVERTIME <", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeLessThanOrEqualTo(String value) {
            addCriterion("DELIVERTIME <=", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeLike(String value) {
            addCriterion("DELIVERTIME like", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeNotLike(String value) {
            addCriterion("DELIVERTIME not like", value, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeIn(List<String> values) {
            addCriterion("DELIVERTIME in", values, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeNotIn(List<String> values) {
            addCriterion("DELIVERTIME not in", values, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeBetween(String value1, String value2) {
            addCriterion("DELIVERTIME between", value1, value2, "delivertime");
            return (Criteria) this;
        }

        public Criteria andDelivertimeNotBetween(String value1, String value2) {
            addCriterion("DELIVERTIME not between", value1, value2, "delivertime");
            return (Criteria) this;
        }

        public Criteria andFailreasonIsNull() {
            addCriterion("FAILREASON is null");
            return (Criteria) this;
        }

        public Criteria andFailreasonIsNotNull() {
            addCriterion("FAILREASON is not null");
            return (Criteria) this;
        }

        public Criteria andFailreasonEqualTo(String value) {
            addCriterion("FAILREASON =", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotEqualTo(String value) {
            addCriterion("FAILREASON <>", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonGreaterThan(String value) {
            addCriterion("FAILREASON >", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonGreaterThanOrEqualTo(String value) {
            addCriterion("FAILREASON >=", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonLessThan(String value) {
            addCriterion("FAILREASON <", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonLessThanOrEqualTo(String value) {
            addCriterion("FAILREASON <=", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonLike(String value) {
            addCriterion("FAILREASON like", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotLike(String value) {
            addCriterion("FAILREASON not like", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonIn(List<String> values) {
            addCriterion("FAILREASON in", values, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotIn(List<String> values) {
            addCriterion("FAILREASON not in", values, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonBetween(String value1, String value2) {
            addCriterion("FAILREASON between", value1, value2, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotBetween(String value1, String value2) {
            addCriterion("FAILREASON not between", value1, value2, "failreason");
            return (Criteria) this;
        }

        public Criteria andLogisticsidIsNull() {
            addCriterion("LOGISTICSID is null");
            return (Criteria) this;
        }

        public Criteria andLogisticsidIsNotNull() {
            addCriterion("LOGISTICSID is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticsidEqualTo(String value) {
            addCriterion("LOGISTICSID =", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidNotEqualTo(String value) {
            addCriterion("LOGISTICSID <>", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidGreaterThan(String value) {
            addCriterion("LOGISTICSID >", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidGreaterThanOrEqualTo(String value) {
            addCriterion("LOGISTICSID >=", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidLessThan(String value) {
            addCriterion("LOGISTICSID <", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidLessThanOrEqualTo(String value) {
            addCriterion("LOGISTICSID <=", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidLike(String value) {
            addCriterion("LOGISTICSID like", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidNotLike(String value) {
            addCriterion("LOGISTICSID not like", value, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidIn(List<String> values) {
            addCriterion("LOGISTICSID in", values, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidNotIn(List<String> values) {
            addCriterion("LOGISTICSID not in", values, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidBetween(String value1, String value2) {
            addCriterion("LOGISTICSID between", value1, value2, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andLogisticsidNotBetween(String value1, String value2) {
            addCriterion("LOGISTICSID not between", value1, value2, "logisticsid");
            return (Criteria) this;
        }

        public Criteria andWaybillnoIsNull() {
            addCriterion("WAYBILLNO is null");
            return (Criteria) this;
        }

        public Criteria andWaybillnoIsNotNull() {
            addCriterion("WAYBILLNO is not null");
            return (Criteria) this;
        }

        public Criteria andWaybillnoEqualTo(String value) {
            addCriterion("WAYBILLNO =", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotEqualTo(String value) {
            addCriterion("WAYBILLNO <>", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoGreaterThan(String value) {
            addCriterion("WAYBILLNO >", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoGreaterThanOrEqualTo(String value) {
            addCriterion("WAYBILLNO >=", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoLessThan(String value) {
            addCriterion("WAYBILLNO <", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoLessThanOrEqualTo(String value) {
            addCriterion("WAYBILLNO <=", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoLike(String value) {
            addCriterion("WAYBILLNO like", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotLike(String value) {
            addCriterion("WAYBILLNO not like", value, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoIn(List<String> values) {
            addCriterion("WAYBILLNO in", values, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotIn(List<String> values) {
            addCriterion("WAYBILLNO not in", values, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoBetween(String value1, String value2) {
            addCriterion("WAYBILLNO between", value1, value2, "waybillno");
            return (Criteria) this;
        }

        public Criteria andWaybillnoNotBetween(String value1, String value2) {
            addCriterion("WAYBILLNO not between", value1, value2, "waybillno");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusIsNull() {
            addCriterion("LOGISTICSSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusIsNotNull() {
            addCriterion("LOGISTICSSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusEqualTo(String value) {
            addCriterion("LOGISTICSSTATUS =", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusNotEqualTo(String value) {
            addCriterion("LOGISTICSSTATUS <>", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusGreaterThan(String value) {
            addCriterion("LOGISTICSSTATUS >", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusGreaterThanOrEqualTo(String value) {
            addCriterion("LOGISTICSSTATUS >=", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusLessThan(String value) {
            addCriterion("LOGISTICSSTATUS <", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusLessThanOrEqualTo(String value) {
            addCriterion("LOGISTICSSTATUS <=", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusLike(String value) {
            addCriterion("LOGISTICSSTATUS like", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusNotLike(String value) {
            addCriterion("LOGISTICSSTATUS not like", value, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusIn(List<String> values) {
            addCriterion("LOGISTICSSTATUS in", values, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusNotIn(List<String> values) {
            addCriterion("LOGISTICSSTATUS not in", values, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusBetween(String value1, String value2) {
            addCriterion("LOGISTICSSTATUS between", value1, value2, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusNotBetween(String value1, String value2) {
            addCriterion("LOGISTICSSTATUS not between", value1, value2, "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkIsNull() {
            addCriterion("LOGISTICSREMARK is null");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkIsNotNull() {
            addCriterion("LOGISTICSREMARK is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkEqualTo(String value) {
            addCriterion("LOGISTICSREMARK =", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkNotEqualTo(String value) {
            addCriterion("LOGISTICSREMARK <>", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkGreaterThan(String value) {
            addCriterion("LOGISTICSREMARK >", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkGreaterThanOrEqualTo(String value) {
            addCriterion("LOGISTICSREMARK >=", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkLessThan(String value) {
            addCriterion("LOGISTICSREMARK <", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkLessThanOrEqualTo(String value) {
            addCriterion("LOGISTICSREMARK <=", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkLike(String value) {
            addCriterion("LOGISTICSREMARK like", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkNotLike(String value) {
            addCriterion("LOGISTICSREMARK not like", value, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkIn(List<String> values) {
            addCriterion("LOGISTICSREMARK in", values, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkNotIn(List<String> values) {
            addCriterion("LOGISTICSREMARK not in", values, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkBetween(String value1, String value2) {
            addCriterion("LOGISTICSREMARK between", value1, value2, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkNotBetween(String value1, String value2) {
            addCriterion("LOGISTICSREMARK not between", value1, value2, "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNull() {
            addCriterion("PAYTIME is null");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNotNull() {
            addCriterion("PAYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andPaytimeEqualTo(Long value) {
            addCriterion("PAYTIME =", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotEqualTo(Long value) {
            addCriterion("PAYTIME <>", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThan(Long value) {
            addCriterion("PAYTIME >", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThanOrEqualTo(Long value) {
            addCriterion("PAYTIME >=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThan(Long value) {
            addCriterion("PAYTIME <", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThanOrEqualTo(Long value) {
            addCriterion("PAYTIME <=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeIn(List<Long> values) {
            addCriterion("PAYTIME in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotIn(List<Long> values) {
            addCriterion("PAYTIME not in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeBetween(Long value1, Long value2) {
            addCriterion("PAYTIME between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotBetween(Long value1, Long value2) {
            addCriterion("PAYTIME not between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andParentnameIsNull() {
            addCriterion("PARENTNAME is null");
            return (Criteria) this;
        }

        public Criteria andParentnameIsNotNull() {
            addCriterion("PARENTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andParentnameEqualTo(String value) {
            addCriterion("PARENTNAME =", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameNotEqualTo(String value) {
            addCriterion("PARENTNAME <>", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameGreaterThan(String value) {
            addCriterion("PARENTNAME >", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTNAME >=", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameLessThan(String value) {
            addCriterion("PARENTNAME <", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameLessThanOrEqualTo(String value) {
            addCriterion("PARENTNAME <=", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameLike(String value) {
            addCriterion("PARENTNAME like", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameNotLike(String value) {
            addCriterion("PARENTNAME not like", value, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameIn(List<String> values) {
            addCriterion("PARENTNAME in", values, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameNotIn(List<String> values) {
            addCriterion("PARENTNAME not in", values, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameBetween(String value1, String value2) {
            addCriterion("PARENTNAME between", value1, value2, "parentname");
            return (Criteria) this;
        }

        public Criteria andParentnameNotBetween(String value1, String value2) {
            addCriterion("PARENTNAME not between", value1, value2, "parentname");
            return (Criteria) this;
        }

        public Criteria andReceiveridIsNull() {
            addCriterion("RECEIVERID is null");
            return (Criteria) this;
        }

        public Criteria andReceiveridIsNotNull() {
            addCriterion("RECEIVERID is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveridEqualTo(String value) {
            addCriterion("RECEIVERID =", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridNotEqualTo(String value) {
            addCriterion("RECEIVERID <>", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridGreaterThan(String value) {
            addCriterion("RECEIVERID >", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridGreaterThanOrEqualTo(String value) {
            addCriterion("RECEIVERID >=", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridLessThan(String value) {
            addCriterion("RECEIVERID <", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridLessThanOrEqualTo(String value) {
            addCriterion("RECEIVERID <=", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridLike(String value) {
            addCriterion("RECEIVERID like", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridNotLike(String value) {
            addCriterion("RECEIVERID not like", value, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridIn(List<String> values) {
            addCriterion("RECEIVERID in", values, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridNotIn(List<String> values) {
            addCriterion("RECEIVERID not in", values, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridBetween(String value1, String value2) {
            addCriterion("RECEIVERID between", value1, value2, "receiverid");
            return (Criteria) this;
        }

        public Criteria andReceiveridNotBetween(String value1, String value2) {
            addCriterion("RECEIVERID not between", value1, value2, "receiverid");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNull() {
            addCriterion("ORDERTIME is null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNotNull() {
            addCriterion("ORDERTIME is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeEqualTo(Long value) {
            addCriterion("ORDERTIME =", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotEqualTo(Long value) {
            addCriterion("ORDERTIME <>", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThan(Long value) {
            addCriterion("ORDERTIME >", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDERTIME >=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThan(Long value) {
            addCriterion("ORDERTIME <", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThanOrEqualTo(Long value) {
            addCriterion("ORDERTIME <=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIn(List<Long> values) {
            addCriterion("ORDERTIME in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotIn(List<Long> values) {
            addCriterion("ORDERTIME not in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeBetween(Long value1, Long value2) {
            addCriterion("ORDERTIME between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotBetween(Long value1, Long value2) {
            addCriterion("ORDERTIME not between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andTotalamountIsNull() {
            addCriterion("TOTALAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotalamountIsNotNull() {
            addCriterion("TOTALAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalamountEqualTo(Long value) {
            addCriterion("TOTALAMOUNT =", value, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountNotEqualTo(Long value) {
            addCriterion("TOTALAMOUNT <>", value, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountGreaterThan(Long value) {
            addCriterion("TOTALAMOUNT >", value, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountGreaterThanOrEqualTo(Long value) {
            addCriterion("TOTALAMOUNT >=", value, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountLessThan(Long value) {
            addCriterion("TOTALAMOUNT <", value, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountLessThanOrEqualTo(Long value) {
            addCriterion("TOTALAMOUNT <=", value, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountIn(List<Long> values) {
            addCriterion("TOTALAMOUNT in", values, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountNotIn(List<Long> values) {
            addCriterion("TOTALAMOUNT not in", values, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountBetween(Long value1, Long value2) {
            addCriterion("TOTALAMOUNT between", value1, value2, "totalamount");
            return (Criteria) this;
        }

        public Criteria andTotalamountNotBetween(Long value1, Long value2) {
            addCriterion("TOTALAMOUNT not between", value1, value2, "totalamount");
            return (Criteria) this;
        }

        public Criteria andFreightpriceIsNull() {
            addCriterion("FREIGHTPRICE is null");
            return (Criteria) this;
        }

        public Criteria andFreightpriceIsNotNull() {
            addCriterion("FREIGHTPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andFreightpriceEqualTo(Long value) {
            addCriterion("FREIGHTPRICE =", value, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceNotEqualTo(Long value) {
            addCriterion("FREIGHTPRICE <>", value, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceGreaterThan(Long value) {
            addCriterion("FREIGHTPRICE >", value, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("FREIGHTPRICE >=", value, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceLessThan(Long value) {
            addCriterion("FREIGHTPRICE <", value, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceLessThanOrEqualTo(Long value) {
            addCriterion("FREIGHTPRICE <=", value, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceIn(List<Long> values) {
            addCriterion("FREIGHTPRICE in", values, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceNotIn(List<Long> values) {
            addCriterion("FREIGHTPRICE not in", values, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceBetween(Long value1, Long value2) {
            addCriterion("FREIGHTPRICE between", value1, value2, "freightprice");
            return (Criteria) this;
        }

        public Criteria andFreightpriceNotBetween(Long value1, Long value2) {
            addCriterion("FREIGHTPRICE not between", value1, value2, "freightprice");
            return (Criteria) this;
        }

        public Criteria andTaketimeIsNull() {
            addCriterion("TAKETIME is null");
            return (Criteria) this;
        }

        public Criteria andTaketimeIsNotNull() {
            addCriterion("TAKETIME is not null");
            return (Criteria) this;
        }

        public Criteria andTaketimeEqualTo(Long value) {
            addCriterion("TAKETIME =", value, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeNotEqualTo(Long value) {
            addCriterion("TAKETIME <>", value, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeGreaterThan(Long value) {
            addCriterion("TAKETIME >", value, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeGreaterThanOrEqualTo(Long value) {
            addCriterion("TAKETIME >=", value, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeLessThan(Long value) {
            addCriterion("TAKETIME <", value, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeLessThanOrEqualTo(Long value) {
            addCriterion("TAKETIME <=", value, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeIn(List<Long> values) {
            addCriterion("TAKETIME in", values, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeNotIn(List<Long> values) {
            addCriterion("TAKETIME not in", values, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeBetween(Long value1, Long value2) {
            addCriterion("TAKETIME between", value1, value2, "taketime");
            return (Criteria) this;
        }

        public Criteria andTaketimeNotBetween(Long value1, Long value2) {
            addCriterion("TAKETIME not between", value1, value2, "taketime");
            return (Criteria) this;
        }

        public Criteria andOrderidLikeInsensitive(String value) {
            addCriterion("upper(ORDERID) like", value.toUpperCase(), "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLikeInsensitive(String value) {
            addCriterion("upper(ORDERSTATUS) like", value.toUpperCase(), "orderstatus");
            return (Criteria) this;
        }

        public Criteria andDelivertimeLikeInsensitive(String value) {
            addCriterion("upper(DELIVERTIME) like", value.toUpperCase(), "delivertime");
            return (Criteria) this;
        }

        public Criteria andFailreasonLikeInsensitive(String value) {
            addCriterion("upper(FAILREASON) like", value.toUpperCase(), "failreason");
            return (Criteria) this;
        }

        public Criteria andLogisticsidLikeInsensitive(String value) {
            addCriterion("upper(LOGISTICSID) like", value.toUpperCase(), "logisticsid");
            return (Criteria) this;
        }

        public Criteria andWaybillnoLikeInsensitive(String value) {
            addCriterion("upper(WAYBILLNO) like", value.toUpperCase(), "waybillno");
            return (Criteria) this;
        }

        public Criteria andLogisticsstatusLikeInsensitive(String value) {
            addCriterion("upper(LOGISTICSSTATUS) like", value.toUpperCase(), "logisticsstatus");
            return (Criteria) this;
        }

        public Criteria andLogisticsremarkLikeInsensitive(String value) {
            addCriterion("upper(LOGISTICSREMARK) like", value.toUpperCase(), "logisticsremark");
            return (Criteria) this;
        }

        public Criteria andUseridLikeInsensitive(String value) {
            addCriterion("upper(USERID) like", value.toUpperCase(), "userid");
            return (Criteria) this;
        }

        public Criteria andParentnameLikeInsensitive(String value) {
            addCriterion("upper(PARENTNAME) like", value.toUpperCase(), "parentname");
            return (Criteria) this;
        }

        public Criteria andReceiveridLikeInsensitive(String value) {
            addCriterion("upper(RECEIVERID) like", value.toUpperCase(), "receiverid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 21 20:00:28 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}