package com.joyveb.cashmanage.entity;

public class OrderInfo extends OrderInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ORDERSTATUS
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.DELIVERTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String delivertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.FAILREASON
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String failreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.LOGISTICSID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String logisticsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.WAYBILLNO
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String waybillno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.LOGISTICSSTATUS
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String logisticsstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.LOGISTICSREMARK
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String logisticsremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.PAYTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private Long paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.USERID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.PARENTNAME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String parentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.RECEIVERID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private String receiverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ORDERTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private Long ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.TOTALAMOUNT
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private Long totalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.FREIGHTPRICE
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private Long freightprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.TAKETIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    private Long taketime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ORDERSTATUS
     *
     * @return the value of t_order_info.ORDERSTATUS
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ORDERSTATUS
     *
     * @param orderstatus the value for t_order_info.ORDERSTATUS
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.DELIVERTIME
     *
     * @return the value of t_order_info.DELIVERTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getDelivertime() {
        return delivertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.DELIVERTIME
     *
     * @param delivertime the value for t_order_info.DELIVERTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setDelivertime(String delivertime) {
        this.delivertime = delivertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.FAILREASON
     *
     * @return the value of t_order_info.FAILREASON
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getFailreason() {
        return failreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.FAILREASON
     *
     * @param failreason the value for t_order_info.FAILREASON
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setFailreason(String failreason) {
        this.failreason = failreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.LOGISTICSID
     *
     * @return the value of t_order_info.LOGISTICSID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getLogisticsid() {
        return logisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.LOGISTICSID
     *
     * @param logisticsid the value for t_order_info.LOGISTICSID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setLogisticsid(String logisticsid) {
        this.logisticsid = logisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.WAYBILLNO
     *
     * @return the value of t_order_info.WAYBILLNO
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getWaybillno() {
        return waybillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.WAYBILLNO
     *
     * @param waybillno the value for t_order_info.WAYBILLNO
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setWaybillno(String waybillno) {
        this.waybillno = waybillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.LOGISTICSSTATUS
     *
     * @return the value of t_order_info.LOGISTICSSTATUS
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getLogisticsstatus() {
        return logisticsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.LOGISTICSSTATUS
     *
     * @param logisticsstatus the value for t_order_info.LOGISTICSSTATUS
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setLogisticsstatus(String logisticsstatus) {
        this.logisticsstatus = logisticsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.LOGISTICSREMARK
     *
     * @return the value of t_order_info.LOGISTICSREMARK
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getLogisticsremark() {
        return logisticsremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.LOGISTICSREMARK
     *
     * @param logisticsremark the value for t_order_info.LOGISTICSREMARK
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setLogisticsremark(String logisticsremark) {
        this.logisticsremark = logisticsremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.PAYTIME
     *
     * @return the value of t_order_info.PAYTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public Long getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.PAYTIME
     *
     * @param paytime the value for t_order_info.PAYTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setPaytime(Long paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.USERID
     *
     * @return the value of t_order_info.USERID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.USERID
     *
     * @param userid the value for t_order_info.USERID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.PARENTNAME
     *
     * @return the value of t_order_info.PARENTNAME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getParentname() {
        return parentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.PARENTNAME
     *
     * @param parentname the value for t_order_info.PARENTNAME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setParentname(String parentname) {
        this.parentname = parentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.RECEIVERID
     *
     * @return the value of t_order_info.RECEIVERID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public String getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.RECEIVERID
     *
     * @param receiverid the value for t_order_info.RECEIVERID
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setReceiverid(String receiverid) {
        this.receiverid = receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ORDERTIME
     *
     * @return the value of t_order_info.ORDERTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public Long getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ORDERTIME
     *
     * @param ordertime the value for t_order_info.ORDERTIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setOrdertime(Long ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.TOTALAMOUNT
     *
     * @return the value of t_order_info.TOTALAMOUNT
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public Long getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.TOTALAMOUNT
     *
     * @param totalamount the value for t_order_info.TOTALAMOUNT
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.FREIGHTPRICE
     *
     * @return the value of t_order_info.FREIGHTPRICE
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public Long getFreightprice() {
        return freightprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.FREIGHTPRICE
     *
     * @param freightprice the value for t_order_info.FREIGHTPRICE
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setFreightprice(Long freightprice) {
        this.freightprice = freightprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.TAKETIME
     *
     * @return the value of t_order_info.TAKETIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public Long getTaketime() {
        return taketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.TAKETIME
     *
     * @param taketime the value for t_order_info.TAKETIME
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    public void setTaketime(Long taketime) {
        this.taketime = taketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderInfo other = (OrderInfo) that;
        return (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()))
            && (this.getOrderstatus() == null ? other.getOrderstatus() == null : this.getOrderstatus().equals(other.getOrderstatus()))
            && (this.getDelivertime() == null ? other.getDelivertime() == null : this.getDelivertime().equals(other.getDelivertime()))
            && (this.getFailreason() == null ? other.getFailreason() == null : this.getFailreason().equals(other.getFailreason()))
            && (this.getLogisticsid() == null ? other.getLogisticsid() == null : this.getLogisticsid().equals(other.getLogisticsid()))
            && (this.getWaybillno() == null ? other.getWaybillno() == null : this.getWaybillno().equals(other.getWaybillno()))
            && (this.getLogisticsstatus() == null ? other.getLogisticsstatus() == null : this.getLogisticsstatus().equals(other.getLogisticsstatus()))
            && (this.getLogisticsremark() == null ? other.getLogisticsremark() == null : this.getLogisticsremark().equals(other.getLogisticsremark()))
            && (this.getPaytime() == null ? other.getPaytime() == null : this.getPaytime().equals(other.getPaytime()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getParentname() == null ? other.getParentname() == null : this.getParentname().equals(other.getParentname()))
            && (this.getReceiverid() == null ? other.getReceiverid() == null : this.getReceiverid().equals(other.getReceiverid()))
            && (this.getOrdertime() == null ? other.getOrdertime() == null : this.getOrdertime().equals(other.getOrdertime()))
            && (this.getTotalamount() == null ? other.getTotalamount() == null : this.getTotalamount().equals(other.getTotalamount()))
            && (this.getFreightprice() == null ? other.getFreightprice() == null : this.getFreightprice().equals(other.getFreightprice()))
            && (this.getTaketime() == null ? other.getTaketime() == null : this.getTaketime().equals(other.getTaketime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        result = prime * result + ((getOrderstatus() == null) ? 0 : getOrderstatus().hashCode());
        result = prime * result + ((getDelivertime() == null) ? 0 : getDelivertime().hashCode());
        result = prime * result + ((getFailreason() == null) ? 0 : getFailreason().hashCode());
        result = prime * result + ((getLogisticsid() == null) ? 0 : getLogisticsid().hashCode());
        result = prime * result + ((getWaybillno() == null) ? 0 : getWaybillno().hashCode());
        result = prime * result + ((getLogisticsstatus() == null) ? 0 : getLogisticsstatus().hashCode());
        result = prime * result + ((getLogisticsremark() == null) ? 0 : getLogisticsremark().hashCode());
        result = prime * result + ((getPaytime() == null) ? 0 : getPaytime().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getParentname() == null) ? 0 : getParentname().hashCode());
        result = prime * result + ((getReceiverid() == null) ? 0 : getReceiverid().hashCode());
        result = prime * result + ((getOrdertime() == null) ? 0 : getOrdertime().hashCode());
        result = prime * result + ((getTotalamount() == null) ? 0 : getTotalamount().hashCode());
        result = prime * result + ((getFreightprice() == null) ? 0 : getFreightprice().hashCode());
        result = prime * result + ((getTaketime() == null) ? 0 : getTaketime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_info
     *
     * @mbggenerated Mon Aug 21 20:00:28 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderstatus=").append(orderstatus);
        sb.append(", delivertime=").append(delivertime);
        sb.append(", failreason=").append(failreason);
        sb.append(", logisticsid=").append(logisticsid);
        sb.append(", waybillno=").append(waybillno);
        sb.append(", logisticsstatus=").append(logisticsstatus);
        sb.append(", logisticsremark=").append(logisticsremark);
        sb.append(", paytime=").append(paytime);
        sb.append(", userid=").append(userid);
        sb.append(", parentname=").append(parentname);
        sb.append(", receiverid=").append(receiverid);
        sb.append(", ordertime=").append(ordertime);
        sb.append(", totalamount=").append(totalamount);
        sb.append(", freightprice=").append(freightprice);
        sb.append(", taketime=").append(taketime);
        sb.append("]");
        return sb.toString();
    }
}