package com.joyveb.cashmanage.entity;

public class ReceiverInfo extends ReceiverInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_receiver_info.RECEIVER
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_receiver_info.ADDRESS
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_receiver_info.PHONE
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    private Long phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_receiver_info.USERID
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_receiver_info.ISDEFAULT
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    private String isdefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_receiver_info.RECEIVER
     *
     * @return the value of t_receiver_info.RECEIVER
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_receiver_info.RECEIVER
     *
     * @param receiver the value for t_receiver_info.RECEIVER
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_receiver_info.ADDRESS
     *
     * @return the value of t_receiver_info.ADDRESS
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_receiver_info.ADDRESS
     *
     * @param address the value for t_receiver_info.ADDRESS
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_receiver_info.PHONE
     *
     * @return the value of t_receiver_info.PHONE
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_receiver_info.PHONE
     *
     * @param phone the value for t_receiver_info.PHONE
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_receiver_info.USERID
     *
     * @return the value of t_receiver_info.USERID
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_receiver_info.USERID
     *
     * @param userid the value for t_receiver_info.USERID
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_receiver_info.ISDEFAULT
     *
     * @return the value of t_receiver_info.ISDEFAULT
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public String getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_receiver_info.ISDEFAULT
     *
     * @param isdefault the value for t_receiver_info.ISDEFAULT
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReceiverInfo other = (ReceiverInfo) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getReceiver() == null ? other.getReceiver() == null : this.getReceiver().equals(other.getReceiver()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getIsdefault() == null ? other.getIsdefault() == null : this.getIsdefault().equals(other.getIsdefault()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getReceiver() == null) ? 0 : getReceiver().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getIsdefault() == null) ? 0 : getIsdefault().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receiver_info
     *
     * @mbggenerated Mon Sep 12 16:36:06 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", receiver=").append(receiver);
        sb.append(", address=").append(address);
        sb.append(", phone=").append(phone);
        sb.append(", userid=").append(userid);
        sb.append(", isdefault=").append(isdefault);
        sb.append("]");
        return sb.toString();
    }
}