package com.joyveb.cashmanage.entity;

public class StockManage extends StockManageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_manage.TOTAL
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    private Long total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_manage.UPDATETIME
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    private Long updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_manage.TOTAL
     *
     * @return the value of t_stock_manage.TOTAL
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_manage.TOTAL
     *
     * @param total the value for t_stock_manage.TOTAL
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_manage.UPDATETIME
     *
     * @return the value of t_stock_manage.UPDATETIME
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_manage.UPDATETIME
     *
     * @param updatetime the value for t_stock_manage.UPDATETIME
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StockManage other = (StockManage) that;
        return (this.getGamecode() == null ? other.getGamecode() == null : this.getGamecode().equals(other.getGamecode()))
            && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGamecode() == null) ? 0 : getGamecode().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_manage
     *
     * @mbggenerated Mon Mar 13 15:04:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", total=").append(total);
        sb.append(", updatetime=").append(updatetime);
        sb.append("]");
        return sb.toString();
    }
}