package com.joyveb.cashmanage.entity;

public class TerminalKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ips_terminal.SESSIONID
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    private String sessionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ips_terminal.SESSIONID
     *
     * @return the value of t_ips_terminal.SESSIONID
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ips_terminal.SESSIONID
     *
     * @param sessionid the value for t_ips_terminal.SESSIONID
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TerminalKey other = (TerminalKey) that;
        return (this.getSessionid() == null ? other.getSessionid() == null : this.getSessionid().equals(other.getSessionid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSessionid() == null) ? 0 : getSessionid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ips_terminal
     *
     * @mbggenerated Wed Nov 30 11:07:10 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sessionid=").append(sessionid);
        sb.append("]");
        return sb.toString();
    }
}