package com.joyveb.cashmanage.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TransferRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    *
    * @generated Fri Mar 10 15:45:26 CST 2017
    */
    protected int offset;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    *
    * @generated Fri Mar 10 15:45:26 CST 2017
    */
    protected int limit;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    protected String sumCol;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    protected String groupSelClause;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public TransferRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    *
    * @generated Fri Mar 10 15:45:26 CST 2017
    */
    public void setOffset(int offset) {
         this.offset = offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    *
    * @generated Fri Mar 10 15:45:26 CST 2017
    */
    public int getOffset() {
          return offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    *
    * @generated Fri Mar 10 15:45:26 CST 2017
    */
    public void setLimit(int limit) {
         this.limit = limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    *
    * @generated Fri Mar 10 15:45:26 CST 2017
    */
    public int getLimit() {
          return limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    public String getSumCol() {
          return sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    public String getGroupSelClause() {
          return groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table t_acc_transferrecord
    */
    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOuttradenumIsNull() {
            addCriterion("OUTTRADENUM is null");
            return (Criteria) this;
        }

        public Criteria andOuttradenumIsNotNull() {
            addCriterion("OUTTRADENUM is not null");
            return (Criteria) this;
        }

        public Criteria andOuttradenumEqualTo(String value) {
            addCriterion("OUTTRADENUM =", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumNotEqualTo(String value) {
            addCriterion("OUTTRADENUM <>", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumGreaterThan(String value) {
            addCriterion("OUTTRADENUM >", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumGreaterThanOrEqualTo(String value) {
            addCriterion("OUTTRADENUM >=", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumLessThan(String value) {
            addCriterion("OUTTRADENUM <", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumLessThanOrEqualTo(String value) {
            addCriterion("OUTTRADENUM <=", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumLike(String value) {
            addCriterion("OUTTRADENUM like", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumNotLike(String value) {
            addCriterion("OUTTRADENUM not like", value, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumIn(List<String> values) {
            addCriterion("OUTTRADENUM in", values, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumNotIn(List<String> values) {
            addCriterion("OUTTRADENUM not in", values, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumBetween(String value1, String value2) {
            addCriterion("OUTTRADENUM between", value1, value2, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andOuttradenumNotBetween(String value1, String value2) {
            addCriterion("OUTTRADENUM not between", value1, value2, "outtradenum");
            return (Criteria) this;
        }

        public Criteria andTransfertypeIsNull() {
            addCriterion("TRANSFERTYPE is null");
            return (Criteria) this;
        }

        public Criteria andTransfertypeIsNotNull() {
            addCriterion("TRANSFERTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTransfertypeEqualTo(String value) {
            addCriterion("TRANSFERTYPE =", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeNotEqualTo(String value) {
            addCriterion("TRANSFERTYPE <>", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeGreaterThan(String value) {
            addCriterion("TRANSFERTYPE >", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFERTYPE >=", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeLessThan(String value) {
            addCriterion("TRANSFERTYPE <", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeLessThanOrEqualTo(String value) {
            addCriterion("TRANSFERTYPE <=", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeLike(String value) {
            addCriterion("TRANSFERTYPE like", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeNotLike(String value) {
            addCriterion("TRANSFERTYPE not like", value, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeIn(List<String> values) {
            addCriterion("TRANSFERTYPE in", values, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeNotIn(List<String> values) {
            addCriterion("TRANSFERTYPE not in", values, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeBetween(String value1, String value2) {
            addCriterion("TRANSFERTYPE between", value1, value2, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransfertypeNotBetween(String value1, String value2) {
            addCriterion("TRANSFERTYPE not between", value1, value2, "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransferoutIsNull() {
            addCriterion("TRANSFEROUT is null");
            return (Criteria) this;
        }

        public Criteria andTransferoutIsNotNull() {
            addCriterion("TRANSFEROUT is not null");
            return (Criteria) this;
        }

        public Criteria andTransferoutEqualTo(String value) {
            addCriterion("TRANSFEROUT =", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutNotEqualTo(String value) {
            addCriterion("TRANSFEROUT <>", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutGreaterThan(String value) {
            addCriterion("TRANSFEROUT >", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFEROUT >=", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutLessThan(String value) {
            addCriterion("TRANSFEROUT <", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutLessThanOrEqualTo(String value) {
            addCriterion("TRANSFEROUT <=", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutLike(String value) {
            addCriterion("TRANSFEROUT like", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutNotLike(String value) {
            addCriterion("TRANSFEROUT not like", value, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutIn(List<String> values) {
            addCriterion("TRANSFEROUT in", values, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutNotIn(List<String> values) {
            addCriterion("TRANSFEROUT not in", values, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutBetween(String value1, String value2) {
            addCriterion("TRANSFEROUT between", value1, value2, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferoutNotBetween(String value1, String value2) {
            addCriterion("TRANSFEROUT not between", value1, value2, "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferinIsNull() {
            addCriterion("TRANSFERIN is null");
            return (Criteria) this;
        }

        public Criteria andTransferinIsNotNull() {
            addCriterion("TRANSFERIN is not null");
            return (Criteria) this;
        }

        public Criteria andTransferinEqualTo(String value) {
            addCriterion("TRANSFERIN =", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinNotEqualTo(String value) {
            addCriterion("TRANSFERIN <>", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinGreaterThan(String value) {
            addCriterion("TRANSFERIN >", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFERIN >=", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinLessThan(String value) {
            addCriterion("TRANSFERIN <", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinLessThanOrEqualTo(String value) {
            addCriterion("TRANSFERIN <=", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinLike(String value) {
            addCriterion("TRANSFERIN like", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinNotLike(String value) {
            addCriterion("TRANSFERIN not like", value, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinIn(List<String> values) {
            addCriterion("TRANSFERIN in", values, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinNotIn(List<String> values) {
            addCriterion("TRANSFERIN not in", values, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinBetween(String value1, String value2) {
            addCriterion("TRANSFERIN between", value1, value2, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferinNotBetween(String value1, String value2) {
            addCriterion("TRANSFERIN not between", value1, value2, "transferin");
            return (Criteria) this;
        }

        public Criteria andTransferamountIsNull() {
            addCriterion("TRANSFERAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTransferamountIsNotNull() {
            addCriterion("TRANSFERAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTransferamountEqualTo(BigDecimal value) {
            addCriterion("TRANSFERAMOUNT =", value, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountNotEqualTo(BigDecimal value) {
            addCriterion("TRANSFERAMOUNT <>", value, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountGreaterThan(BigDecimal value) {
            addCriterion("TRANSFERAMOUNT >", value, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANSFERAMOUNT >=", value, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountLessThan(BigDecimal value) {
            addCriterion("TRANSFERAMOUNT <", value, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANSFERAMOUNT <=", value, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountIn(List<BigDecimal> values) {
            addCriterion("TRANSFERAMOUNT in", values, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountNotIn(List<BigDecimal> values) {
            addCriterion("TRANSFERAMOUNT not in", values, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANSFERAMOUNT between", value1, value2, "transferamount");
            return (Criteria) this;
        }

        public Criteria andTransferamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANSFERAMOUNT not between", value1, value2, "transferamount");
            return (Criteria) this;
        }

        public Criteria andFactorageIsNull() {
            addCriterion("FACTORAGE is null");
            return (Criteria) this;
        }

        public Criteria andFactorageIsNotNull() {
            addCriterion("FACTORAGE is not null");
            return (Criteria) this;
        }

        public Criteria andFactorageEqualTo(BigDecimal value) {
            addCriterion("FACTORAGE =", value, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageNotEqualTo(BigDecimal value) {
            addCriterion("FACTORAGE <>", value, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageGreaterThan(BigDecimal value) {
            addCriterion("FACTORAGE >", value, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FACTORAGE >=", value, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageLessThan(BigDecimal value) {
            addCriterion("FACTORAGE <", value, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FACTORAGE <=", value, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageIn(List<BigDecimal> values) {
            addCriterion("FACTORAGE in", values, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageNotIn(List<BigDecimal> values) {
            addCriterion("FACTORAGE not in", values, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FACTORAGE between", value1, value2, "factorage");
            return (Criteria) this;
        }

        public Criteria andFactorageNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FACTORAGE not between", value1, value2, "factorage");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTradenumIsNull() {
            addCriterion("TRADENUM is null");
            return (Criteria) this;
        }

        public Criteria andTradenumIsNotNull() {
            addCriterion("TRADENUM is not null");
            return (Criteria) this;
        }

        public Criteria andTradenumEqualTo(String value) {
            addCriterion("TRADENUM =", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumNotEqualTo(String value) {
            addCriterion("TRADENUM <>", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumGreaterThan(String value) {
            addCriterion("TRADENUM >", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumGreaterThanOrEqualTo(String value) {
            addCriterion("TRADENUM >=", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumLessThan(String value) {
            addCriterion("TRADENUM <", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumLessThanOrEqualTo(String value) {
            addCriterion("TRADENUM <=", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumLike(String value) {
            addCriterion("TRADENUM like", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumNotLike(String value) {
            addCriterion("TRADENUM not like", value, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumIn(List<String> values) {
            addCriterion("TRADENUM in", values, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumNotIn(List<String> values) {
            addCriterion("TRADENUM not in", values, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumBetween(String value1, String value2) {
            addCriterion("TRADENUM between", value1, value2, "tradenum");
            return (Criteria) this;
        }

        public Criteria andTradenumNotBetween(String value1, String value2) {
            addCriterion("TRADENUM not between", value1, value2, "tradenum");
            return (Criteria) this;
        }

        public Criteria andMessageidsIsNull() {
            addCriterion("MESSAGEIDS is null");
            return (Criteria) this;
        }

        public Criteria andMessageidsIsNotNull() {
            addCriterion("MESSAGEIDS is not null");
            return (Criteria) this;
        }

        public Criteria andMessageidsEqualTo(String value) {
            addCriterion("MESSAGEIDS =", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsNotEqualTo(String value) {
            addCriterion("MESSAGEIDS <>", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsGreaterThan(String value) {
            addCriterion("MESSAGEIDS >", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGEIDS >=", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsLessThan(String value) {
            addCriterion("MESSAGEIDS <", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsLessThanOrEqualTo(String value) {
            addCriterion("MESSAGEIDS <=", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsLike(String value) {
            addCriterion("MESSAGEIDS like", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsNotLike(String value) {
            addCriterion("MESSAGEIDS not like", value, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsIn(List<String> values) {
            addCriterion("MESSAGEIDS in", values, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsNotIn(List<String> values) {
            addCriterion("MESSAGEIDS not in", values, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsBetween(String value1, String value2) {
            addCriterion("MESSAGEIDS between", value1, value2, "messageids");
            return (Criteria) this;
        }

        public Criteria andMessageidsNotBetween(String value1, String value2) {
            addCriterion("MESSAGEIDS not between", value1, value2, "messageids");
            return (Criteria) this;
        }

        public Criteria andTransfertimeIsNull() {
            addCriterion("TRANSFERTIME is null");
            return (Criteria) this;
        }

        public Criteria andTransfertimeIsNotNull() {
            addCriterion("TRANSFERTIME is not null");
            return (Criteria) this;
        }

        public Criteria andTransfertimeEqualTo(Long value) {
            addCriterion("TRANSFERTIME =", value, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeNotEqualTo(Long value) {
            addCriterion("TRANSFERTIME <>", value, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeGreaterThan(Long value) {
            addCriterion("TRANSFERTIME >", value, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeGreaterThanOrEqualTo(Long value) {
            addCriterion("TRANSFERTIME >=", value, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeLessThan(Long value) {
            addCriterion("TRANSFERTIME <", value, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeLessThanOrEqualTo(Long value) {
            addCriterion("TRANSFERTIME <=", value, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeIn(List<Long> values) {
            addCriterion("TRANSFERTIME in", values, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeNotIn(List<Long> values) {
            addCriterion("TRANSFERTIME not in", values, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeBetween(Long value1, Long value2) {
            addCriterion("TRANSFERTIME between", value1, value2, "transfertime");
            return (Criteria) this;
        }

        public Criteria andTransfertimeNotBetween(Long value1, Long value2) {
            addCriterion("TRANSFERTIME not between", value1, value2, "transfertime");
            return (Criteria) this;
        }

        public Criteria andFailreasonIsNull() {
            addCriterion("FAILREASON is null");
            return (Criteria) this;
        }

        public Criteria andFailreasonIsNotNull() {
            addCriterion("FAILREASON is not null");
            return (Criteria) this;
        }

        public Criteria andFailreasonEqualTo(String value) {
            addCriterion("FAILREASON =", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotEqualTo(String value) {
            addCriterion("FAILREASON <>", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonGreaterThan(String value) {
            addCriterion("FAILREASON >", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonGreaterThanOrEqualTo(String value) {
            addCriterion("FAILREASON >=", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonLessThan(String value) {
            addCriterion("FAILREASON <", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonLessThanOrEqualTo(String value) {
            addCriterion("FAILREASON <=", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonLike(String value) {
            addCriterion("FAILREASON like", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotLike(String value) {
            addCriterion("FAILREASON not like", value, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonIn(List<String> values) {
            addCriterion("FAILREASON in", values, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotIn(List<String> values) {
            addCriterion("FAILREASON not in", values, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonBetween(String value1, String value2) {
            addCriterion("FAILREASON between", value1, value2, "failreason");
            return (Criteria) this;
        }

        public Criteria andFailreasonNotBetween(String value1, String value2) {
            addCriterion("FAILREASON not between", value1, value2, "failreason");
            return (Criteria) this;
        }

        public Criteria andOuttradenumLikeInsensitive(String value) {
            addCriterion("upper(OUTTRADENUM) like", value.toUpperCase(), "outtradenum");
            return (Criteria) this;
        }

        public Criteria andTransfertypeLikeInsensitive(String value) {
            addCriterion("upper(TRANSFERTYPE) like", value.toUpperCase(), "transfertype");
            return (Criteria) this;
        }

        public Criteria andTransferoutLikeInsensitive(String value) {
            addCriterion("upper(TRANSFEROUT) like", value.toUpperCase(), "transferout");
            return (Criteria) this;
        }

        public Criteria andTransferinLikeInsensitive(String value) {
            addCriterion("upper(TRANSFERIN) like", value.toUpperCase(), "transferin");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andTradenumLikeInsensitive(String value) {
            addCriterion("upper(TRADENUM) like", value.toUpperCase(), "tradenum");
            return (Criteria) this;
        }

        public Criteria andMessageidsLikeInsensitive(String value) {
            addCriterion("upper(MESSAGEIDS) like", value.toUpperCase(), "messageids");
            return (Criteria) this;
        }

        public Criteria andFailreasonLikeInsensitive(String value) {
            addCriterion("upper(FAILREASON) like", value.toUpperCase(), "failreason");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 10 15:45:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_acc_transferrecord
     *
     * @mbggenerated Fri Mar 10 15:45:26 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}