package com.joyveb.auth.restful.bean;

public class AdminOperator extends AdminOperatorKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.PASS_WORD
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.REAL_NAME
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.RETRY
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private Short retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.STATUS
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.CREATE_DATE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.LAST_DATE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private Long lastDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.ROLE_CODE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private String roleCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.PASS_WORD
     *
     * @return the value of T_ADMIN_OPERATOR.PASS_WORD
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.PASS_WORD
     *
     * @param passWord the value for T_ADMIN_OPERATOR.PASS_WORD
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.REAL_NAME
     *
     * @return the value of T_ADMIN_OPERATOR.REAL_NAME
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.REAL_NAME
     *
     * @param realName the value for T_ADMIN_OPERATOR.REAL_NAME
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.RETRY
     *
     * @return the value of T_ADMIN_OPERATOR.RETRY
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public Short getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.RETRY
     *
     * @param retry the value for T_ADMIN_OPERATOR.RETRY
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setRetry(Short retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.STATUS
     *
     * @return the value of T_ADMIN_OPERATOR.STATUS
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.STATUS
     *
     * @param status the value for T_ADMIN_OPERATOR.STATUS
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.CREATE_DATE
     *
     * @return the value of T_ADMIN_OPERATOR.CREATE_DATE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.CREATE_DATE
     *
     * @param createDate the value for T_ADMIN_OPERATOR.CREATE_DATE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.LAST_DATE
     *
     * @return the value of T_ADMIN_OPERATOR.LAST_DATE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public Long getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.LAST_DATE
     *
     * @param lastDate the value for T_ADMIN_OPERATOR.LAST_DATE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setLastDate(Long lastDate) {
        this.lastDate = lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.ROLE_CODE
     *
     * @return the value of T_ADMIN_OPERATOR.ROLE_CODE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.ROLE_CODE
     *
     * @param roleCode the value for T_ADMIN_OPERATOR.ROLE_CODE
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminOperator other = (AdminOperator) that;
        return (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getPassWord() == null ? other.getPassWord() == null : this.getPassWord().equals(other.getPassWord()))
            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
            && (this.getRetry() == null ? other.getRetry() == null : this.getRetry().equals(other.getRetry()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getLastDate() == null ? other.getLastDate() == null : this.getLastDate().equals(other.getLastDate()))
            && (this.getRoleCode() == null ? other.getRoleCode() == null : this.getRoleCode().equals(other.getRoleCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPassWord() == null) ? 0 : getPassWord().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getRetry() == null) ? 0 : getRetry().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getLastDate() == null) ? 0 : getLastDate().hashCode());
        result = prime * result + ((getRoleCode() == null) ? 0 : getRoleCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", passWord=").append(passWord);
        sb.append(", realName=").append(realName);
        sb.append(", retry=").append(retry);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastDate=").append(lastDate);
        sb.append(", roleCode=").append(roleCode);
        sb.append("]");
        return sb.toString();
    }
}