package com.joyveb.auth.restful.bean;

import java.io.Serializable;

public class AdminOperatorKey implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.USER_NAME
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.USER_NAME
     *
     * @return the value of T_ADMIN_OPERATOR.USER_NAME
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.USER_NAME
     *
     * @param userName the value for T_ADMIN_OPERATOR.USER_NAME
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminOperatorKey other = (AdminOperatorKey) that;
        return (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Fri Apr 15 21:03:14 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append("]");
        return sb.toString();
    }
}