package com.joyveb.auth.restful.bean;

public class LogLoginKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_LOGIN.UUID
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_LOGIN.UUID
     *
     * @return the value of T_LOG_LOGIN.UUID
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_LOGIN.UUID
     *
     * @param uuid the value for T_LOG_LOGIN.UUID
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_LOGIN
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LogLoginKey other = (LogLoginKey) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_LOGIN
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_LOGIN
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append("]");
        return sb.toString();
    }
}