package com.joyveb.auth.restful.bean;

public class LogLogin extends LogLoginKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_LOGIN.USER_NAME
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_LOGIN.ACTION
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_LOGIN.IP
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOG_LOGIN.CREATE_DATE
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    private Long createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_LOGIN.USER_NAME
     *
     * @return the value of T_LOG_LOGIN.USER_NAME
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_LOGIN.USER_NAME
     *
     * @param userName the value for T_LOG_LOGIN.USER_NAME
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_LOGIN.ACTION
     *
     * @return the value of T_LOG_LOGIN.ACTION
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_LOGIN.ACTION
     *
     * @param action the value for T_LOG_LOGIN.ACTION
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_LOGIN.IP
     *
     * @return the value of T_LOG_LOGIN.IP
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_LOGIN.IP
     *
     * @param ip the value for T_LOG_LOGIN.IP
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOG_LOGIN.CREATE_DATE
     *
     * @return the value of T_LOG_LOGIN.CREATE_DATE
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOG_LOGIN.CREATE_DATE
     *
     * @param createDate the value for T_LOG_LOGIN.CREATE_DATE
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_LOGIN
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LogLogin other = (LogLogin) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getAction() == null ? other.getAction() == null : this.getAction().equals(other.getAction()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_LOGIN
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getAction() == null) ? 0 : getAction().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOG_LOGIN
     *
     * @mbggenerated Wed Apr 13 16:15:45 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", action=").append(action);
        sb.append(", ip=").append(ip);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }
}