package com.joyveb.auth.restful.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.joyveb.auth.restful.bean.AdminOperator;
import com.joyveb.auth.restful.bean.AdminOperatorExample;
import com.joyveb.auth.restful.bean.AdminOperatorKey;

public interface AdminOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @SelectProvider(type=AdminOperatorSqlProvider.class, method="countByExample")
    int countByExample(AdminOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @DeleteProvider(type=AdminOperatorSqlProvider.class, method="deleteByExample")
    int deleteByExample(AdminOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Delete({
        "delete from t_admin_operator",
        "where USER_NAME = #{userName,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(AdminOperatorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Insert({
        "insert into t_admin_operator (USER_NAME, PASS_WORD, ",
        "REAL_NAME, RETRY, ",
        "STATUS, CREATE_DATE, ",
        "LAST_DATE, ROLE_CODE)",
        "values (#{userName,jdbcType=VARCHAR}, #{passWord,jdbcType=VARCHAR}, ",
        "#{realName,jdbcType=VARCHAR}, #{retry,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=DECIMAL}, #{createDate,jdbcType=DECIMAL}, ",
        "#{lastDate,jdbcType=DECIMAL}, #{roleCode,jdbcType=VARCHAR})"
    })
    int insert(AdminOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @InsertProvider(type=AdminOperatorSqlProvider.class, method="insertSelective")
    int insertSelective(AdminOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @SelectProvider(type=AdminOperatorSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="USER_NAME", property="userName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PASS_WORD", property="passWord", jdbcType=JdbcType.VARCHAR),
        @Result(column="REAL_NAME", property="realName", jdbcType=JdbcType.VARCHAR),
        @Result(column="RETRY", property="retry", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.DECIMAL),
        @Result(column="LAST_DATE", property="lastDate", jdbcType=JdbcType.DECIMAL),
        @Result(column="ROLE_CODE", property="roleCode", jdbcType=JdbcType.VARCHAR)
    })
    List<AdminOperator> selectByExample(AdminOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Select({
        "select",
        "USER_NAME, PASS_WORD, REAL_NAME, RETRY, STATUS, CREATE_DATE, LAST_DATE, ROLE_CODE",
        "from t_admin_operator",
        "where USER_NAME = #{userName,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="USER_NAME", property="userName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PASS_WORD", property="passWord", jdbcType=JdbcType.VARCHAR),
        @Result(column="REAL_NAME", property="realName", jdbcType=JdbcType.VARCHAR),
        @Result(column="RETRY", property="retry", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.DECIMAL),
        @Result(column="LAST_DATE", property="lastDate", jdbcType=JdbcType.DECIMAL),
        @Result(column="ROLE_CODE", property="roleCode", jdbcType=JdbcType.VARCHAR)
    })
    AdminOperator selectByPrimaryKey(AdminOperatorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminOperatorSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AdminOperator record, @Param("example") AdminOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminOperatorSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AdminOperator record, @Param("example") AdminOperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminOperatorSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AdminOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_operator
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Update({
        "update t_admin_operator",
        "set PASS_WORD = #{passWord,jdbcType=VARCHAR},",
          "REAL_NAME = #{realName,jdbcType=VARCHAR},",
          "RETRY = #{retry,jdbcType=DECIMAL},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "CREATE_DATE = #{createDate,jdbcType=DECIMAL},",
          "LAST_DATE = #{lastDate,jdbcType=DECIMAL},",
          "ROLE_CODE = #{roleCode,jdbcType=VARCHAR}",
        "where USER_NAME = #{userName,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AdminOperator record);
}