package com.joyveb.auth.restful.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.joyveb.auth.restful.bean.AdminPermission;
import com.joyveb.auth.restful.bean.AdminPermissionExample;
import com.joyveb.auth.restful.bean.AdminPermissionKey;

public interface AdminPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @SelectProvider(type=AdminPermissionSqlProvider.class, method="countByExample")
    int countByExample(AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @DeleteProvider(type=AdminPermissionSqlProvider.class, method="deleteByExample")
    int deleteByExample(AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Delete({
        "delete from t_admin_permission",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(AdminPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Insert({
        "insert into t_admin_permission (ID, PID, ",
        "NAME, URL, LEAF, ",
        "STATUS, ORDER_ID, ",
        "ICON)",
        "values (#{id,jdbcType=DECIMAL}, #{pid,jdbcType=DECIMAL}, ",
        "#{name,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{leaf,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=DECIMAL}, #{orderId,jdbcType=DECIMAL}, ",
        "#{icon,jdbcType=VARCHAR})"
    })
    int insert(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @InsertProvider(type=AdminPermissionSqlProvider.class, method="insertSelective")
    int insertSelective(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @SelectProvider(type=AdminPermissionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PID", property="pid", jdbcType=JdbcType.DECIMAL),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEAF", property="leaf", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ICON", property="icon", jdbcType=JdbcType.VARCHAR)
    })
    List<AdminPermission> selectByExample(AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Select({
        "select",
        "ID, PID, NAME, URL, LEAF, STATUS, ORDER_ID, ICON",
        "from t_admin_permission",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PID", property="pid", jdbcType=JdbcType.DECIMAL),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEAF", property="leaf", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ICON", property="icon", jdbcType=JdbcType.VARCHAR)
    })
    AdminPermission selectByPrimaryKey(AdminPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminPermissionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AdminPermission record, @Param("example") AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminPermissionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AdminPermission record, @Param("example") AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminPermissionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Update({
        "update t_admin_permission",
        "set PID = #{pid,jdbcType=DECIMAL},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "URL = #{url,jdbcType=VARCHAR},",
          "LEAF = #{leaf,jdbcType=DECIMAL},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "ORDER_ID = #{orderId,jdbcType=DECIMAL},",
          "ICON = #{icon,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(AdminPermission record);
}