package com.joyveb.auth.restful.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.joyveb.auth.restful.bean.AdminRolePermission;
import com.joyveb.auth.restful.bean.AdminRolePermissionExample;
import com.joyveb.auth.restful.bean.AdminRolePermissionKey;

public interface AdminRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @SelectProvider(type=AdminRolePermissionSqlProvider.class, method="countByExample")
    int countByExample(AdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @DeleteProvider(type=AdminRolePermissionSqlProvider.class, method="deleteByExample")
    int deleteByExample(AdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Delete({
        "delete from t_admin_role_permission",
        "where ROLE_CODE = #{roleCode,jdbcType=VARCHAR}",
          "and PERMISSION_ID = #{permissionId,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(AdminRolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Insert({
        "insert into t_admin_role_permission (ROLE_CODE, PERMISSION_ID, ",
        "FIELD1)",
        "values (#{roleCode,jdbcType=VARCHAR}, #{permissionId,jdbcType=DECIMAL}, ",
        "#{field1,jdbcType=DECIMAL})"
    })
    int insert(AdminRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @InsertProvider(type=AdminRolePermissionSqlProvider.class, method="insertSelective")
    int insertSelective(AdminRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @SelectProvider(type=AdminRolePermissionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ROLE_CODE", property="roleCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PERMISSION_ID", property="permissionId", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="FIELD1", property="field1", jdbcType=JdbcType.DECIMAL)
    })
    List<AdminRolePermission> selectByExample(AdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Select({
        "select",
        "ROLE_CODE, PERMISSION_ID, FIELD1",
        "from t_admin_role_permission",
        "where ROLE_CODE = #{roleCode,jdbcType=VARCHAR}",
          "and PERMISSION_ID = #{permissionId,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ROLE_CODE", property="roleCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PERMISSION_ID", property="permissionId", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="FIELD1", property="field1", jdbcType=JdbcType.DECIMAL)
    })
    AdminRolePermission selectByPrimaryKey(AdminRolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminRolePermissionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AdminRolePermission record, @Param("example") AdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminRolePermissionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AdminRolePermission record, @Param("example") AdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @UpdateProvider(type=AdminRolePermissionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AdminRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role_permission
     *
     * @mbggenerated Wed Mar 23 11:14:04 CST 2016
     */
    @Update({
        "update t_admin_role_permission",
        "set FIELD1 = #{field1,jdbcType=DECIMAL}",
        "where ROLE_CODE = #{roleCode,jdbcType=VARCHAR}",
          "and PERMISSION_ID = #{permissionId,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(AdminRolePermission record);
}